(function () {
  "use strict";
  var vLSSaltQueueFormationLo = "SaltQueueFormationLocker";
  var vLS20260725persistentow = "20260725-persistent-owned-response-v6";
  var vLN8 = 8;
  var vLN5 = 5;
  var vLN15 = 1.5;
  var vLN05 = 0.5;
  var vLN21600000 = 21600000;
  var vLN15552000000 = 15552000000;
  var vLN1200 = 1200;
  var vLSBabayuSaltFieldForma = "Babayu.SaltField.FormationCache.v3";
  var vLN250 = 250;
  var vLN750 = 750;
  var vLN2 = 2;
  var vO = {};
  if (window[vLSSaltQueueFormationLo] && typeof window[vLSSaltQueueFormationLo].destroy === "function") {
    window[vLSSaltQueueFormationLo].destroy();
  }
  var vVO2 = {
    "101": "司马懿",
    "102": "郭嘉",
    "103": "关羽",
    "104": "诸葛亮",
    "105": "周瑜",
    "106": "太史慈",
    "107": "吕布",
    "108": "华佗",
    "109": "甄姬",
    "110": "黄月英",
    "111": "孙策",
    "112": "贾诩",
    "113": "曹仁",
    "114": "姜维",
    "115": "孙坚",
    "116": "公孙瓒",
    "117": "典韦",
    "118": "赵云",
    "119": "大乔",
    "120": "张角",
    "201": "徐晃",
    "202": "荀彧",
    "203": "小典韦",
    "204": "张飞",
    "205": "小赵云",
    "206": "庞统",
    "207": "鲁肃",
    "208": "陆逊",
    "209": "甘宁",
    "210": "貂蝉",
    "211": "董卓",
    "212": "小张角",
    "213": "张辽",
    "214": "夏侯惇",
    "215": "许褚",
    "216": "夏侯渊",
    "217": "魏延",
    "218": "黄忠",
    "219": "马超",
    "220": "马岱",
    "221": "吕蒙",
    "222": "黄盖",
    "223": "蔡文姬",
    "224": "小乔",
    "225": "袁绍",
    "226": "华雄",
    "227": "颜良",
    "228": "文丑",
    "301": "周泰",
    "302": "许攸",
    "303": "于禁",
    "304": "张星彩",
    "305": "关银屏",
    "306": "关平",
    "307": "程普",
    "308": "张昭",
    "309": "陆绩",
    "310": "吕玲绮",
    "311": "潘凤",
    "312": "邢道荣",
    "313": "祝融夫人",
    "314": "孟获"
  };
  var vA = [{
    label: "合力",
    heroes: ["吕布", "赵云"]
  }, {
    label: "吴国",
    heroes: ["周瑜", "孙策"]
  }, {
    label: "关羽",
    heroes: ["关羽"]
  }, {
    label: "姜维",
    heroes: ["姜维"]
  }, {
    label: "毒爆",
    heroes: ["张角", "华佗"]
  }, {
    label: "三蜀",
    heroes: ["诸葛亮", "黄月英", "赵云"]
  }, {
    label: "典韦",
    heroes: ["典韦"]
  }, {
    label: "司马",
    heroes: ["司马懿"]
  }, {
    label: "吕布",
    heroes: ["吕布"]
  }];
  var vA2 = [[223, "蔡文姬", "caiwenji", "DQkHDQkHDQkHDQcEDggDDgkFDQkHDQkHDQoHCw0LDAoHDggDDwgCDQgEDAkHDQkHCgsKBRATCgoIDgkEEQsHEQsGDggFDQkHBgoMBw0PCQkIDwoGGRUOFxEMDggFDQkHAhAWBQwQBQwPDwwKGhYPFhAMDQkHDQkH"], [113, "曹仁", "caoren", "DQkHDAgGDwoEDQkGDAkHDQoIDQkHDQkHDAkHCQYFDgkDDQkGDgwJEhEODQkHDQkHDQkHDQgFEAgDDQgEEQ8MFhYSDQkIDQkHDAkICgkKCwsLDAcHDQkJDgoKCwgIDAoJCwkIDQwMCwsMDQoJDwkIDgkIDAgIDAoJ"], [113, "曹仁", "caoren2", "DQkHDQkHDQkHDQkIDQkHDQkHDQkHDQkHDQkHDwoGCgsKCwoKCwcFDwkDDgsGDQkHDAgGCwgGCg0LBQwPCQkJCgcGCgkICwsJCwkICgoLCQoLBgsOBwkLDg4NCAkKCQwNCg0ODQ4PDwwLCQkJBAsPCQwOCgoKDwsI"], [113, "曹仁", "caoren3", "DQkHDQkHDQkHDwsGDwwGDQkHDQkHDQkHDQkHDQkHDQgGDgkGDwwFDwwIDQoIDQkHDQkHDgkFEgsEEAkFDgkGExEPEA0KDQkHDgkGEAoCFA4CEwwFExEMFhUSEg0IDwgDDQgFEwwCDggDEQoDFhAGGhYIFhADDggC"], [113, "曹仁", "caoren4", "DQkHDQkHDAgHDAcGDAkHDQoIDQkHDQkHDQkHDAkHCwYGCgUGEA0LExIPDQkIDQkHDQkHCwgHCQQFDAgFEg8LFxYTDQkIDQkHDwcIDAcJDAUGCwYGDQkJDgoKDAcGDQkHDwkGEgkGEwcHEQkHEQsJCgsMDwgHDggG"], [113, "曹仁", "caoren5", "DQoHDxMNDg4JDwwJEg4MDwwJDQkHDQkHDQkHDQwIEQ4JGBUQFREOEQ4LEQ0JDQkHDQkHDQkHFRELGRYRDgoIEQ8MFRMODgoHDQkHDAkHFBAJFxMLEQ0HFxYRFhQPDgoHDAkHCgcHEAsFFA8FFA8EExAGDgwEDAkH"], [113, "曹仁", "caoren6", "DQkHDAgGCgYFCgcGCgcFCgYFDAgHDQkHDAkHCQYFCQYGCQYGCQUFDQkHCgcGDQkHDAkHCwcGCgUFCQYFDQoHFBMPCwgHCwgGDAgGCQYFCQUFDAgFDwsHFBMQDAkICwgGCgYFDAkIEhAODgwLCQYGCwgICgcGDQkI"], [113, "曹仁", "caoren7", "DQkHDAkICwkIBwgLCwoJDAoIDQkHDQkHDAwLCwwNBg8TBAoPBw8RCRAUCwoKDQkHDRYYCREWBRUdBBMYDg8MChESDAsLCQsOChYcCBMcBhEbBxAXDgwIDAwLCQ0RBg4VEA0QDhQVDxITCBIZCgkMCgcIBwkQCAwT"], [113, "曹仁", "caoren8", "DQkHDQkHBwUFBAMECgcGDAkHDQkHDQkHDQkHDAgHCAQEBAMDCgYEDwsIDgsIDQkHDQkHDAcGCwUFBwQECwcEEQ8MEQ0KEAsGCgcGDAkGDgoGDgoGDQkGDgsKDQgIDwoGBAMEBQUGBgUFDQkFEQwGDwkFEAoFEQ0I"], [307, "程普", "chengpu", "DQkHDAkHDQgGDgkFDgkGDwoGDgkHDQkHDAkHCgYGEAcFEQoFEQwGEQwHEQwIDQoHDAkHCgUFEQcEEAoFDwsDEQwHGRMKEAwIDAkHCgYFDgUEEAkEEAkEFQ8HHBYLEg0IDAkHDAgGDAcEDwkFEgkDDggDFhAHEAsG"], [119, "大乔", "daqiao", "DQkHDQkHEggHEwgHEwgIDQcGDQkHDQkHDQkHDAgHEQYGDQYGDQcIDggIDAcHDQkHDQkHDwcHEQYGDAYIEgwKFg0MDggJDAgHDQkHEwcHDgUHDggJFhAPGxYUEQwLDAkHDQkHDQcGDAUGDQcIFhAPGhUTEAwKDQkH"], [119, "大乔", "daqiao2", "DQkHDQkIDwwOFhEMFREOFBEODQkIDQkHDQkHDQkJDw0UExEVFBAQEw4NDQkLDQkIDQkHDQkJDgsSEhAYFA8QFhAMDwsNDQkIDQkHDQkIDgoPEg0TGBESHBcUEAwKDQkHDQkHDQkHDQgIDwcIFg8QGBMRDwoIDQkH"], [119, "大乔", "daqiao3", "DQkHDQkHDQkHDQkHEQsGEgsFDQkHDQkHDQkHDQkHDwgGEAcFFggGFgcFDwgGDQkHDAsLCwwMCgoLEwgFFwkFFwgGEAgGDQkHChIVBxEWCg0ODQgIEgkIFQoIEQkGDgoIChIXEQwVEggKFAkHEQkIFQwKFAkHFgkP"], [119, "大乔", "daqiao4", "DQkHDQsIDg4KDw8LERAKDg0JDQoHDQkHDQkHDQwIDw4JDgoHDwoJDgkJDgkHDQkHDQkHDQgGEgsFDggHEQwLFRANDAcIDAkHDQkHDAgHCgUGDggJGBIQGhUTDgoJDQkHDAgHDAgHCwYGEA0NFxMRFxQSEhAQDQkH"], [119, "大乔", "daqiao5", "DQkHDQkHDwgGEwgFEAgGDQgGDQkHDQkHDQkHDQoIEAoIDQYFDwgFDQgGDAgHDQkHDQkHEQ4MEA0MCwYHFA8NFA8NDgoJDQoIDgsJFRIPEQ4NEgwMGxUTGhUSDgoJDQkIDQoIExAOFBEOEgsHFg8NFA0LDgkICwYH"], [119, "大乔", "daqiao6", "DQkHDQkHDgkHDQgFCwQDDggFDQkHDQkHDAkHCwYFDQcFDQgHDAUECwUEDAcGDQkHDAkHCgUECQQECgUFEQsKDgkJCgcHDQkHDQkHDAgHCwkJEAoIGxYTFBANDAkIDQkHDQkHDQkHDwsHFAwHFQ8LFA0IDgkHDQkH"], [119, "大乔", "daqiao7", "DQkHDQkHDgoGEg0EDwgDDgkFDQkHDQkHDQkHEQ4IEQ0GDgoFDwoHDgkHDAkHDQkHDQoHExEJCwkGCggHGBMQFRAODAkHDgoHFxEEGxYHDgwHCggHGRQSFxMREAsFFg8DHhgDGxgHCwkHCQcHFRAODwwKEQoFFAoE"], [117, "典韦", "dianwei", "DQkHDQkHDQkHDgkHDwoHEwwJDQkHDQkHDQkHDQkHFAkHFAgGFgwJFg0KDgoIDQkHDQkHDwgHFwsJEwsFGA8KGA4KEAkHDQkHDAkHDQgHEw0LFwwJGg4LGAwJEAsKDQkHDAcGCwcEDAgGEwwKGg4LFQwKDAkJDQkH"], [117, "典韦", "dianwei2", "DQkHDQkHDQkHDgkHEAoIEgwJDQkHDQkHDgoHDwoGDwoGFAkGFgsIFw4KDwkHDQkHEQwEEw0DEwwDFQwFFw0IGQ0KFAoGDgkGDQkGCwcGDAcEFAwDFwwIFQsIDwcGEAoFDwkFDggEEAoDEgoDDQkGCwoKDg0ODA0O"], [117, "典韦", "dianwei3", "DQkHDAkHCgkIDAgHDgkGDAkHDQkHDQkHDQkHDgoGCwkHDAgGEQkEDwsFDgoGDQkHDQkHEQsEDwsHEQ0GCwsKDwoGDwoGDQkHDQkHDwoFEgwEEwwDDgsGEAkEDwoFDQkHDQgGDgoFEAkFCggIDggGEAcFDwgFDAsI"], [117, "典韦", "dianwei4", "DQkHDAgICwYKDAYKDQkIDQkHDQkHDQkHDQkHCwYJCgQMDAUJDgkGEQsHDwoIDQkHCwgICAUKCgYJDggGEAkEFg0JFAwJDAkHCQYIBwUKCAcNCggMDwkHFg0JFwwIDAcICgcICAUJBwYKBwcMCQgMEQoGFQsGDggF"], [117, "典韦", "dianwei5", "DQkHDAkIDgsHEw8IDQwLDQkHDQkHDQkHDAoICA8SChESEw4GEA4JEQsJCwwLDAsKDQoIBxEUChAREw0FEgsEEwsICgkICwsLDwoGEA0HDwwHEA8LDQoHDAcFCgYFCgwLDAsKDBAPCRMRCw0MDQkIDwsJEQ8OCwkI"], [117, "典韦", "dianwei6", "DQkHDQkHDQkHCwgGDQgGEgwJDQkHDQkHDQkHDAkHDAcGDwcGEgoIFg4KDwoIDQkHDQkHDAkHDAcGEQkGEwwIFg0KDAcGDAkIDgsJEQ8NDw0MDwoIEQkHDggHCAUFCgYGDw4NEhMTEhMTEA8ODQoJCAUFBwQECgYF"], [117, "典韦", "dianwei7", "DwoFEAsEDgsHCwoJCwsKDQsICwoJDQkHCgkIDgsIFAsGDwoJCQ0OCg0ODQoKDQkHCwkIEwoHFAsGDQoIDwoIFAoHEgkFDgkGDQsLEgoHDwgHCwkJEAsHEQsIEQsEDgkGEgkIEQkFCgUEDggGDQoIDQwIDwoFCwYF"], [210, "貂蝉", "diaochan", "DQkHDAkHDAUFDwcDDgcEDAgGDQkHDQkHDQkHDAgHCwUFDAUEDQYFDAYFDAgHDQkHDQkHCwcGCwUFDwgHEgsIEQoHDAcGDQkHDQkHDAgHDAYFFQ0JHBUOFxAKDQkGDQkHDQkHDQkKEgkGFxALHBUPFg8JDgkGDQkH"], [211, "董卓", "dongzhuo", "DQkHDQkHEAgHDgkFDQkHDQkIDQkHDQkHDQkHDgYFEwgFEwoCDggGDggJDAgHDAkHDQgGDQQDDgUDEQgEDgcFDwcGCgcGCgcGDQkHDQYEDQUDEQgFDAcFCgcGCQcGCgcGDQgGDQYDDgcCDAUFCgUHDAUHCwYJCwYH"], [209, "甘宁", "ganning", "DQkHDAgGDAcFDAcFDQgGDQkHDQkHDQkHDQkHDAcFDAMBDQQCEAkDDwkFDQkHDQkHDQkHDAYEDQMBEAgDFA0EFhEIEQwIDQkHDQkHCwYEDQQDEw0FGBMIGhcPGBQODwsIDQkHCwcGDQgIEAkHFw8IGhgRGRYPEAwJ"], [116, "公孙瓒", "gongsunzan", "DQkHDQkHDAgHCQYGCwcHDQkIDQkHDQkHDQkHDQkHCQYGBgUFCgcHDwwKDAkHDQkHDQkHDAgHBwUFCAYGDQkGEQ4NEA0LDQkHDQgJCgYHDQcDEg0IFRIPFRMRFRQREQwKDAgGDAcDDgcDDwgFEw8MEg8OEQwNEgwO"], [116, "公孙瓒", "gongsunzan2", "DQkHDQkHDQkHDQkGDQkFDQkHDQkHDQkHDQkHDAkHDAkHDQkGDwkEDwkFDQkGDQkHDQkHDQkIDAcIDwkGEwoFEwoJEQkFDQkHDQkIFA4RDAgJDgkHEwoHFAsJEgkGDgkIDgkGEwsFCwcFDwoDDgkFDgoJEQoGDwoG"], [116, "公孙瓒", "gongsunzan3", "DAkHCwYGDgYFDQgFCwcGDAkHDQkHDQkHDAgHCAUFDQgEEAsCCAYFDgsJDQkHDQkHDAkHCQYFDQgDCAUECggGEA0LDgoIDQkHDQkHDQkHCgcFCAUEEA0KFRMREA0KDQkGDQkHDgkFEgsBDggCDQkHFRMSEg0MDwgJ"], [116, "公孙瓒", "gongsunzan4", "DQkHDQkHDAgGCwYEDAcFDQkHDQkHDQkHDQkHDAcFDAYFDwgGDgkIDgsJDAkHDQkHDQkHDAcGCgUECgYEDgoHEg8NDgoIDQkHDQkHCwYECgUDCwcFEQ4LFRMRDwsIDQkIDQkHDAcEEAoEEgwEDwkEEAsHDwgLEQwO"], [116, "公孙瓒", "gongsunzan5", "DQkHEAsGFQ0EEQkEDAgGDQkHDQkHDQkHDQkHEgoDFQoDEQsJCgYHDgoIDQkHDQkHDQkHDgkFDwkECwcGCgcGEAwKDgoIDQkHDQkHCwcGCAUGCwcGDwsJFBEPDwsLDAgJDAgHBwUGDAUEEwsEDwsIEw4KDwkKDggN"], [116, "公孙瓒", "gongsunzan6", "DQkHDQkHDQkHEQsIDQkIDAkHDQkHDQkHDQkHDQkHDQkJDgkHCwgICwgHDAkHDQkHDAkHCQcGCggIBwUGDAkIDwsKDQkHDAkHDAkHCgcGCAYGCQcHDwsJExAPEA4MDQkIDwoMDwsLCwcIDAgKEQwRExAQExAPEA0M"], [116, "公孙瓒", "gongsunzan7", "DQkHDggHFgYGFgYGDQkHDQkHDQkHDQkHDQkHEAYGGAYFEgYGDwsKDQkIDQkHDQkHDQkHEwYGFgYFDQgGDwsKDwwKDQkHDgoJDQkHDgcHEAgIEAoIEw8OExAPDgoKEQ4MDQoIFBISFBETDwkLFw8KFQ0JEQwNDwsJ"], [116, "公孙瓒", "gongsunzan8", "DQkHDAgHCgcGCgcHCgcGDAkHDQoIDQkHDQkHCwgHCQYGDAkHDQoIEA0LEQ4KDgoHDQkHCwgHCQcHEQ4NFhEKGBIKFxIOEAsGDQgLDQcNDwkMEw4KFQ8HFQ8HFA4GEAoFDgYPDQcODwkIGBEIFxEKEAsHDQgFDwoG"], [306, "关平", "guanping", "DQkHDQkHDQkHDQkHDgoIDgoIDQkHDQkHDQkHDQkHDAgHDAgIEQ4MEQ0LDgoIDQkHDQkHDAgHCwgIDQoJExAKExANEQ0KDQkHDQkHDAgHCgYHCwgIEQ4KFxURExAMDQkHCwkHCwgHCQYGCQcHDgwJFxQPEQ0KDAkH"], [305, "关银屏", "guanyinping", "DQkHDAkHCwgJCwkIDAkHDQkHDQkHDQkHDQkHCwgICAYJCQYICwYHCwcIDQkHDQkHDQkHDAgHCAUICwcJDAcIDAcJDAkIDQkHDQkHDQkHCwcIEw0LGBENEgwKDAgHDQkHDQkHDQkHDQkHFQ4LHBUOEgwJDAkHDQkH"], [103, "关羽", "guanyu", "DQkHDQkHDQkHDQkGDwkGEQsIDQkHDQkHDQkHDQkHDAoFDgoDEggFFg0KEQsJDQkHDQkHDQgGCwkEDAgEEQoEFw8MEg0LDQkHDQkHDwYEDQYEDgYDEAcEDQgHCwYGDAkHDggHEQYFDgYEDgYDCwQDCAQFCQUEDAgG"], [103, "关羽", "guanyu13", "DQkHEAwKFBEOEg4MCwYGCwcGCwcGDQkHDQkHEQ0LEhANEg8MEwwJEwwKDwsIDgoHEg0HEQwGDgkGDAcGEQoHFQ8MEAsIEg0HGhQJGxUJGhQJEAoGDgcFCwYGCQYGCwcFGxcQHBkQHRkNGRYMDgwICwgFCAUECwcF"], [103, "关羽", "guanyu2", "DQkHDQkHDQkHDQkHDQkGDQkHDAkHDQoHDQgGDQkFDQkGDgoFDQgFDQkFCgcGDgsFDAkHCgYFCQgFCAcFCgcFCwgFCwgFCQcFDAkHCwcGCQYFCAUFCgkGCggHCgcFCwgGCwgHDAcGDAgGCgcECQcECgYFDAYEDAoH"], [103, "关羽", "guanyu3", "DQkHDQkHDQkGDgoFEAsHEQwJDQkHDQkHDQkHEAoEEQoCEgoBFAsGFxAMDgoIDQkHDQkHEQoDEwoBEwoBEwoGGBIPDwsJDQkHDQkHDgkGDwgDEQkCDAYEDAgHDAcFDQkHDQkHDAgHEAwIEQ0FDAgECAQEDAcFDgkH"], [103, "关羽", "guanyu4", "DQkHDQcGCQUFCQUFDQkHDQoHDQkHDQkHDAkHDgUFCwQEDAgGEgsIEgwJDgoIDQkHDAgHCgQECwUEEwwHFAsHFw4LEQwJDQkHDQkHDAYFDgUEEQkFFAwFFA0JDQkHDAgHDQkHDQYFDAQFDAgGEQsHDgkGCQUFDAgG"], [103, "关羽", "guanyu5", "DQkHDQkHDQkHDgsJEg4LEAoIDQkHDQkHDQkHDQkHDwwKEQ0LEgoHFQ0KDwoIDQkHDQkHDQkHDwwKDQoJDggHFxANDwsJDQkHDQkHDQkHDAgFDAcFDAYFDQgICwcGDQkHDQkHDwwKDAgGCwcFCgYFCQUFDAcGDQkH"], [103, "关羽", "guanyu6", "DQkHEQYEEwQDDggGDgoHDgoHDQoIDQkHDgcGEgQCEAUDDQwIDg4IFQ4JEgwJDgoIDQkHDQUEDAYFCQ8LDg8JFAsHFw8MEQ0KDQkHDwkECwsICA4LDgsGEAkFEQsKDQkIDQkGDQoFCQ4JCg8KDg0HCwUECQYGCQYG"], [103, "关羽", "guanyu7", "DQkHDQkHDgoGDwsGEQwIEQ0JDQkHDQkHDQkHEAwHFQ0EFw8DGA8HGBMNDgoIDQkHDQkHEg0HGBAEGRADFw8GGhUQEg0JDgsHDQkHDgoHFA0FGREFFA0FEwsGFhAGEQ0IDgoHDwoHFRAJHBUJGxYIEQoEGBEHGBIJ"], [103, "关羽", "guanyu8", "DQkHDQoIDgwKDQkHDAkGDAkHDQoHDQkHDQkHDxANDxUSDQsGDAoGCQgGDQsGDQkHDQkHDw0IEBAIDw0GDgwGCgoGDwcFDggGDgoGEQ0GDRAKCw4KEA0JDwsHDAcFDAgGDwsFDQsGCw4JCgwIDAoIDQoJCQcGDAkI"], [102, "郭嘉", "guojia", "DQkHDQkHCwkIBwgKCgYGDQkHDQkHDQkHDQkHDQkGDAkGCAYGCAYGEhAODwwKDQkHDQkHDQkGDAcGCwgFDgwHGRgVExEODQkHDQkHDAkHCwcGCggGDA0MGBcUDxAQDQoIDQkHDAgGDwsIEw8KDAsKCQwNBQwRDAoJ"], [102, "郭嘉", "guojia2", "DQkHDQkHDQkHDQkHDAkHDQkHDQkHDQkHDQkHDAkHCwgHCggICQgIDAoHDwoGDQkHDQkHDAgHCQYFBwYGCAcICggIDgkFDgoGDQkHDQwJCwgGDwsFCw4PCA4RDAsJDwsGDgkGExEICw8ODAoICAsMBwkMDg8ODQ4N"], [102, "郭嘉", "guojia3", "DQkHDgkGEwwCEgsDDAgFDQkIDQkHDQkHDQkHEQkDFw0BDQgDCQcGExEODgsIDQkHDQkHEgoDFgwBDgoDEQ8LGRgVEA0LDQkHDQkHDwgFEQgDCQYGEA0MGBYTEg4MDQkHDQkHDQkHDAsMCgwQCAcLDQoLDAsMDAgI"], [102, "郭嘉", "guojia4", "DQkHDAkHDAkHCwgHCwgHDQkHDQkHDQkHDAkHCggIDAoKCQcHCQYHEQ4NDQoIDQkHCwkICgkICwkICggFDw0KGRcVDgwKDQkHDQoIEQ4LCwkICQcGERANGRkVDgwKDAkHDwwKExEODwwLCQkLCwsLEREPCgsMDAkI"], [102, "郭嘉", "guojia5", "DQkHDAgHCgYGCwcGCgYGCgYGDAgGDQkHDQkHCwgGCgcGCQUFCAUFDAgHDAgGDAkHDQkHCgcGCQUFCAYFCQcFExEPEA0LDQkHDAgHCwcGCgcGCwoJDw4LGRgVFBIQDQkHCwcGCwcGCgcGDwwKDxEPFRYUExIPDQkH"], [102, "郭嘉", "guojia6", "EAoFEwwEEAoFDAkHDAkHDQkHDQkHDQkHEAkEFAwCEAgDCgYGCgcHEAwKDQkHDQkHDAsICw4KDQkIDQoFEA4LFBEPDgoIDQkHCwsJCAwLDQkHCwgGEQ8MEg8NEAwJDQkHDAkHDgkGFg4EEgwEDwkFDwsKEA0JDwoG"], [102, "郭嘉", "guojia7", "DQkHCgYFCAMECQUGCgYGDgsHDwwHDQkHDQkHDAkHCQUFBwQFCwgIEg8LDwsHDQkHDQkHCwcGCAQEDAkEDwsJFRMRDQkHDQkHDQkHDAgGEg4KGRYOFhIKFRIOEw4JDQoHDAkHDgkHFxEMGxYLFxEIEQsIFhAIEg0J"], [222, "黄盖", "huanggai", "DQkHDQkHDgoHDgoHDQsJDQoIDQkHDQkHDQkHDwsIGBQNEw0KDAoJDAwLDAkIDQkHDQkHEAwIFxELEAsHDA0LDQ8ODgsJDQkHDQkHDwsHEgwIDQsJDQ4NFhUQGBQNDQoHDQkHDAkICwoKDgsLDwsKEhANFQ8KDgoH"], [110, "黄月英", "huangyueying", "DQkHDQkHDQgGEgsFEQwFDgkGDQkHDQkHDQkHDgoIEw4HGhMIFxAIFg8IDgoHDQkHDQkHDgoHFxAHGhMJHBYPGRMLEQ0HDQkHDQkHDQkHFA0GFRAIGRUMFREJDwsHDQkHDQkHDQkHEAsGDw0FEREGDw8GDQoHDQkH"], [110, "黄月英", "huangyueying2", "DQkHDQkHDQkHFA8IFRAJDgsIDQkHDQkHDQkHDQkHDQkHEw0GGRUNFhQODwsHDQkHDQkHDQkHDQoHFA4HFxEHFREIEAwGDQkHDgoHEw4HEAwFEA4FFBIHFRIJDw4FDQoHFA8HGREDFA4EEA8EEA8HFRMMDw4GDQoH"], [110, "黄月英", "huangyueying3", "DQkHDgoHEAsFFA4HFxIJEg0GEAsGDQkHDQkHEAsGGREEGhQKGxUMGxUKFA8HDQkHDQkHDwsGGhQHFBAJDwsIFA8HFREJDQkHDQkHDwsGGhMGFQ8IFRALFA8JFA4HDQkHCwgGCwcGEA4FEg0GFhALFA4HDwoGDQkH"], [110, "黄月英", "huangyueying5", "Dw0HEBAGEA8FFA8FFxIEEQ8FEQ8HDgsHEA8HDQsGFA4EFxIDFBEEFBAEDwwGDgsHDw0HDgoHEw0EFRAHGBQLFRAHDwwGDQoHDgsHDgsHEA8GFxIKHBcQFRIKDgwGDQoHDQoHDQoHDgsIEQ0JFhIMEAwJDAoGDQkH"], [110, "黄月英", "huangyueying6", "DgoIEAoHFgkGGxELGxQNGREMFAsHDQkHEA0KEQwJFQwGGA4IFw8JGRMOFQ4JDgoHDQoIEAwIFw8HFw4IGBEMGBINEwwIDQkHDQkHDwsHFQ8IGBMMHBcQGBQNDwsIDQkHDQkHEQsHFw4GFQ8JGRMOFBEMDQoIDQkH"], [110, "黄月英", "huangyueying7", "DQkHEQsGEA0HDg4JDw0IDwsIDQkHDQkHDQkHDwoHFxAHFxMKGBMJGRQKDwsIDQkHDQkHEAsHGhQJGhULGhUOGBMKEAwHDQkHDQkHDQoHFQ8IGBQMHBgQFhELDgoHDQkHDQkHDQkHDwsIFhEMGhUQEg4LDQkHDQkH"], [110, "黄月英", "huangyueying8", "DQkHDwsHGhQHFA8GEg0GGRMHEQ0HDQkHDQkHFA8GGhMFFxEGHRgIHRgIFhEHDQkHDgkHFw8FGhEFGhIFFxEHFxEHEw0GDQkHDQkHEw0FEg8IEg0HFhAKGRMNEw0IDQkHDwoGDg4JDA4JEwwGFA0IFxIMEAoGDQkH"], [110, "黄月英", "huangyueying9", "DQkHDQkHEQoEEQoIDwkGDggEDQkGDQkHDQkHDgkGEgwIDAoLCggJCAcHCQYFDAgHDQoJEA4OEhERCgkKCgkJEA4QCQcICwgHDwwMDQwOCwkLDAoKEg8MFRIQDAkJDAkHDgoKCQgJBwYICQgLDQwNEQ0MCAgJCggI"], [218, "黄忠", "huangzhong", "DQkHDgoIDgoIDgoHDQkHDwwHDQoHDQkHDQkHExEOFA4IEQsFDw0HEhEJEA0JDQkHDQkHEg4LFQ4HEQ8GEhEHFhUPGBYSDgoIDQkHEQ0LEw4JEg0GExIIFhUPGhkVEQ4MDQkHDwsJDgsHDgsFEw8GEw8IEw8KDwsI"], [108, "华佗", "huatuo", "DQkHDAkGCwgFDgsHDAkHCwkIDAkHDQkHDQkHCwgFDAoGEg8MCgoJCQkJCwgHDQkHDQkHDAkGDAkFDQsGDg0IEA8NEhANDQkHDQkHDAgGCQgECQgHDQwLFRQRGRgUDwsJDQkHCwgECAcECgYFCwkHEBANFRMQDgkH"], [108, "华佗", "huatuo2", "DQkHDQkHDQkHDQwHDQoHDQoHDQwHDQoHDQkHDAkHDQkGDg4HEhINEA8KDA4HDQoHDQwIDQsGCwgFEA4KFxYTFhYQDw4IDQoGDA0HDxEGDAsECwkGEg4LFRIOEA0KDAkGCwgGDQoHDgwICwgFDAoGDw0IExANDwwJ"], [108, "华佗", "huatuo3", "DQkHDQkHDg0LEA8NCwkICwkHDAkHDQkHDQkHDg0LERUVEREQCgoJCgkIDAgHDQkHDQkHDg4ODRARDw0HDQwJERAOEQ4MDQkHDQkHDAoJCwoKCgkIDg0LFxYTGBYSDwkGDQkHDQoIEQ4LDw0LCgsLEhIQFhUSEQsI"], [108, "华佗", "huatuo4", "DQkHDQkHDQoIDQkHDAkHCwkIDQkHDQkHDQkHDQkHEg8MDwoICwoJCgkJDgoIDQoIDQoIEA0LEQ4MDAoHDg0KFBMQFxUSDgsJDQoIEg8NEAwKDwoJDw0LExIQFBMQDQoIDgoIEQ4LEQoHEwgEFRAHEw8KEg8LDQoH"], [108, "华佗", "huatuo5", "DQkHDQkHCwkHCQkJCwkHDAkHDQkHDQkHDQkHDgkGCgkHCAkJCQkICgkIDQkHDQkHDQkHEAoHDw0LDw0JDg0MEA4MDQoIDQkHDQkHDwwKFBIPExIPGRQRGw8NFQkICwgGDgsJEw4LEwsIFxUSHA4NHwoJHQoJDwgH"], [108, "华佗", "huatuo6", "DQkHDQkHDQkHDgsJDwwLDAkIDQkHDQkHDQkHCwgHDw0MFhQSDg0MCQkKDAkIDQkHDAkHCgcHEhAOFRMQDw4KDg0NEQ8ODQoICwgHCgcHFBIPExEODQwLEhEPFxUSDgsJDAkHDQsKEhAOEQ8NDw0MDw4NEhAOEQ4N"], [108, "华佗", "huatuo7", "DQkHDQkHDQkHDwwKEg8NDgsJDAkHDQkHDQkHDQkHDgsJFBEPDQsKCQkICgkIDAkHDAkHDQgHDwsJEQ8MDw4LCgkJCgkJDQoIDAoICgkIDQsJDwsJDgsJEA8NERAOEA0KCQkICQsKCQoIDAwGEA0IEAsIDQoHDwsI"], [108, "华佗", "huatuo8", "DQkHDQkHDwgDEAoEEAwIEA4JDgoHDQkHDAkHDAoHDwkEEg0GFA8IFA8HEw0FDwoGCwkHDgsHExAMGBYRFRAKFRAJFREJEw4ICwkFDgwIFA0EGBYRExMNDhIHDA8GExEMDQsGDw8LEAwHFBALEw8IEBEIEA4GEA0I"], [226, "华雄", "huaxiong", "DQkHDQkHCwgGCwcFDAgGDQgHDQkHDQkHDQkHDAgHCwYFDQgFCwcGDwoKDQkIDQkHDQkHCgcGCgYEDQkEDQgFEAsLDwoIDQkHDAkHCAYFCQYFDAgGEAsJFBEOEQ0LDQkHCgYFCQYFDwwKEg8MEQoKEQoPDwgLDwoH"], [114, "姜维", "jiangwei", "DQkHDQkGDggEDQkHDQkIDQkHDQkHDQkHDQkHDAgGDggFDQsJDwsJEAwKDQkHDQkHDQkHDAkHCggIDQsJEg4JFRMSDgoJDQkHDQkHCwgHDgkEEAoFEw8NGBYWEAwKDQkGDAgGDAcEEgoBEQoCDQoGDw0JDAkFDggD"], [114, "姜维", "jiangwei11", "DQkHDAkICggIDQkHDQoIDQkHDQkIDQkHDQoICwoJDAoIDwsGDQoIEAwLDAoJDAoIChERDhITDQwMDgoIEAwJExAQDwwNCg8PCRQTDhYVDhYWCQ8ODAoHEw8JDxALCxISEhYVFBgYEhoaDxcXCQsLEAwEDQ4KDxQU"], [114, "姜维", "jiangwei2", "DQkHDQkHDQkHDQkHDQkGDQkGDQkHDQkHDAkHDAkHDQkHEAwKEw0HEg0KDgkHDAkHDAgHCggGDwsHFRISFg8JFRALEAoFDAoHDAkHCQcGCwsHCwsIEQ8JFREMEAwHDQoHDgoJDAgHCQkICQgGDQkFDAoJCwsJDAoJ"], [114, "姜维", "jiangwei3", "DQkHDQkHDQkHDAkIDAkHDQkHDQkHDQkHDQkHDAkHCggHDAsKDwsJEQwKDQkHDQkHDQkHCwgGCggIDgsIEQ0IExAPDgoJDQkHDQkHDAkHCgcFDAgGEQ0LFhQVEQ4NDAkHDQkHDQkGDgwFCggGDQsIEA8ODgwIDAkG"], [114, "姜维", "jiangwei4", "DQkHCwgGCgcGDQoKDg0ODAoJDQkHDQkHDAkICwkICwoKDg4ODgwMDwsIDQkHDQkHDAgHCggJDAwMDQsKDwsIEQ8ODg0NDQkHCwcGCQcGDAwMDw0MEQ4LERITDg8QDAoJCgYFCwoKEBAREBERDQ0NEBARDg4ODgsK"], [114, "姜维", "jiangwei5", "DQkHEAUEEQQCEQsEFREEEAsFDQkHDQkHDgcFEQIBEAMBFQwCFhADEQwGDwsIDQkHDQcGEAIAEAYCFAoCDwkFEQ0JFBAOEAoGDwYEEAIBEAcCFQsCEAsGFBAOGBYWEQsJDwQCDQYEEQgDEwoEDgoHDgsIFQ8LDwsG"], [114, "姜维", "jiangwei6", "DQkHDQoIFRMQEQ8NCwkIDAkHDQkHDQkHDQoIExANGhgUDw8NDAsJDwwJDQkHDQkHDQoHFBENERAODAwKEQ0KFBEPDQoJDQkHDQkHDwsJDgwJDQsJFBANFxYWEA0NDQkHDQkHDQkHEg4LFRIMExENFRUVFBESDQoI"], [114, "姜维", "jiangwei7", "DQkHDQkHDQkHDgoHEAsGDQkHDQkHDQkHDAgHDQgGCwkHCwwJDgsHEAwJDQkIDQkHDAgGDAgGCg0LCgwKEAwIFBAPDQsKDAkHDAkHCwwJCg4LDA4LEQ4KGBYWERAPDAoICwoICQ0JCQ0KCg8MDgwIEhIQDw8NCwoI"], [114, "姜维", "jiangwei8", "DQkHEQwGFA8GEQ0IEg4IDgoIDQkHDQkHDgoHGRIFGREGFxMNGRUKFA4JDwsIDQkHDgoHGRAFFw8FFhELFxEIGRMLFxMNDwsIEg0GGREFFg8FGRIGFxAIHBgSGxgTEQ0JFQ4FEgwGEw8LFhEMEw4JFhMPFxQQEw4I"], [114, "姜维", "jiangwei9", "DQkHDQkHDQkHEBALCwkHCwkGDAkHDQkHDQkHDQkHDAkHDQ4MDw0JDgsFDQoGDAkHDQkHDwsGCgwJDQwHEg4FEQ4EDw0FCwoHDQkHEA4HDQ4HDw0GEA4GDhAGEA4FDQoGDQoIERIKExQLDw0HCgsHDBEJDhIKDg0I"], [112, "贾诩", "jiaxu", "DQkHDQkHDQkIDAgIDQkHDgoJDQkHDQkHDQkHDAgHCwcNDAYKEQsHEw8ODQoIDQkHDQkHCwcJCggPDgkIEg4IFBEQDwsKDAkHDQkHDAcHCwUIDwoKEhAPFRIRDQkJDQkFDQgGDgcEDwkGEAwKDQoMEQ4PDgkIDggE"], [112, "贾诩", "jiaxu2", "DQkHDQkHDQkHDwoGDwoGDQoHDQkHDQkHDQkHDQkHDQkHEQwFEQwIEg4NDQkJDQkIDAkHDAkKDgsNFRAHFQ8IEwwSDQkQDQsMDQkGEAoFDw0UEQ8TFAwKEwoOEAkLDgoIDQkHEAoLEgoWEA0ZDgkPEgsOEQsHDgkG"], [112, "贾诩", "jiaxu3", "DQkHDgoHEQkOEwkUDgkJDQkHDQkHDQkHEAsFGhQGGhQLEwwRDwkIDwsJDQoIDQkHDgoGFxEEGBEFFQ8JEQwKEg8ODwsKDAkHDAkICwsPDQsNEg4MEg8JExEQEQ0LDQkHDAkHCwkLEQwMGhUMGBMOGBUREg0IEw0H"], [112, "贾诩", "jiaxu4", "DQkHDQkHDAkHCwcGDAcGDgoIDQoIDQkHDQkHDQkHCgYGCgUGDggIEg4NDwsKDQkHDAcFCwYECAQFDAYGEw8KExAOEQ4MDAgHCwYECwYECgYFDAYHFBEQFxQSEAwLDAgHDAgGDggGDwsJEA4NDwoKEAsJDggGDgkI"], [112, "贾诩", "jiaxu5", "DQkHDQkHCggHCgkJCgoJCwsJDQkHDQkHDQkHDAkHBgUFBQgICAoJDQsLDQkIDQkIDQkHDAgIBgUGCAYEDQoIEA0NDAgIDAoLDQkHCwgGCAUGDAgHEhAQEQ8OCwcHDAkIDQkHDAgHCAUJDQgIDw0OEA0NDAgLDQkK"], [112, "贾诩", "jiaxu6", "DQkHDAkHCwgHCwcGCwcHDQkIDQkHDQkHDAkHCgYGCQYHCQYHDQoKEQ0NDQkHDQkHDQkHCgcGCAYHCwgIEQ0LExEQDAkIDQkHDQkHDAgJCQYHEg4MFhQSFBERCwgIDAgIDQkIDAkPCgcNDggHFA0KFA4MDAcICwgJ"], [112, "贾诩", "jiaxu8", "DQkHDQkHDQoKDwsUEQ4SEQ4NDQoMDQkHDQkHDQkIDwsSDwsSEQ4QFBEPDgoLDQkHDQoIEAwMFBEUFhQSFhQUEQ4TEg8NDwsJEQ0LFxUTFhMSFhQTEA8SDQkSFRIQFRIQEQwIEg4MEQ4OFxUSEg8QEg8PFhQRExAN"], [0, "刘备", "liubei", "DQkHDQkHDQkHDAkHCwcFDQoGDQkHDQkHDQkHDQkHDQgFCgYECwgEEA0HDAgGDQkHDQkHDggFDwYBCQQDDAkGDwwHDAgGDQkHDAkHDAgFDgYCCgUDCwkFEA0IDwkFDQkGCwgGCQcEDwgDEggCEQkCEwsEDwgEDQkI"], [210, "貂蝉", "longdiaochan", "DQkHDQkHDAcFEAgDDgcEDgkHDQkHDQkHDQkHDQkHDAYFEQgGDwcFEQkHDQkHDQkHDQkHDAgGCwUFDwgGEAgHEAgHDAgGDQkHDQkHDAgHCwUFEgoIGhIMFQ4JDQgGDQkHDQkHDQkHEAkEFg4JHRYPFxAJDgkGDQkH"], [309, "陆绩", "luji", "DQkHDAgGDAYFDAcFDgkJEQwNDgoIDQkHDQkHCgYFDAYECwUDEg0OFBESEA0MDQkHDQkHDAcFCwUDDQcFEw8LFhUUFRINDAgGDQkHDQYFDAYFDQcGFBERGhgTFxQNDAcGDQkHDwYECwYFCwUDEAoJFxIOFA4KDAgG"], [207, "鲁肃", "lusu", "DQkHDgoGDgkGDQkHDQoIDQ0MDQoIDQkHDQkHDgcGEAYFDAcGDAwLDQ8PDQwLDQkHDQkHDAgGCwcHCggHEBAJEREREQ4NDQoIDQkHDAkHCgcHCggJDQ4NExISFhEQDwoIDQkHDQkHDAcGEQUFEwgGFQ8NFQ0LEAcF"], [207, "鲁肃", "lusu2", "EAoHFAkHDggGDAgHDAsKDQwLDQkHDQkHDQkHDggHDwgGCwgHDA4NDg8PDQoIDQkHDQkHDQkGCwcHDAoIDxENExEQDwsKDQkHDQkHDQkHDwoIEg4LEhEQFxMSEw4MDwoHDQkHDwkGFQwHEwsGEw0IFw8LEwsGEQYF"], [207, "鲁肃", "lusu3", "DQkHDQkHDQkHDQkHDQkHEAsGFRAKDwsIDQkHDQkHDQkHEAkHEAoHEQsHFRALDgoHDQgGDwgGEAoHEQgGFAgGEQkHEQoIEAkHDAcGDQQEEwgGEAkHDggFCwYFDQYGEQcGDQgGEQcFEQgGDwoJEQcFDwgGEQgHEgkH"], [207, "鲁肃", "lusu4", "DQkHDgoHGA4FHREEFg0FEgoFDgkHDQkHDQkHFAwFGQ0DGA0DFwwEFQYEEQgGDQkHDgkGFgwEGQ0CFAsDEwsFEwkGEQcFDwkFDggFEwsEFgsDFQsDGA8GGBAGEwoEEQgDFhAHEQkEEgkEFQwEFgwGGAkFFAcEEQYD"], [207, "鲁肃", "lusu5", "DQkHDgkGEAsGEAsGDQwKDAsKDQkHDQkHEAoGFAoGEA8IDQwHDA0MDQ8ODQoIDAkHDgkFEAgDEAkEDAsIDA0LDg0NDgoHEQwGDwoGEQkEEwwGEQ0IEhAOFBEQEAsIFQwGDQgFEQkEFQsGFgkFFQ0IFQ4KDwkGEwkF"], [207, "鲁肃", "lusu6", "DQkHDQkHEAsGDQgHDAsKDAwLDQkHDQkHDQkHDgoGDQgHCgcIDA4ODQ4ODQoIDQkHEAwKDwsKCwcIDQsIDg8NERAQDgsKDQkHGRgUGhkWFhUTExMSEBEQFhMSEg0MDwkGGBYRFhIMGBYRGhkUFRINGRUTFAsJEwwG"], [208, "陆逊", "luxun", "DQkHDggGEQkHDgoHDgoHEgsJDgkHDQkHDQkHDgUFEAkFDggFEQwIFgwJEAoIDQkHDQkHDQgHCwcGDQgGFA8IGBINFREMDQkHDQkHDQkHCwcGDggHEwwJGhcRGBQPDQgGDQkHDQkHDgoGEggFEggHGhgREw4LDQgG"], [107, "吕布", "lvbu", "DQkHDQkHDwkIEQoJDQkIDAkHDQkHDQkHDQkHEQkIFgkIEwgFDAcFDgsJEAwIDQkHDgkHEggGEwcFDQYDCwcEEg4IGRQMEAwIDwkHEgcGDwcFDQcDDAoGFRILHBcNEw8JDggGEAcFEAcCDwgBEgkCFAsFGBIJEgoE"], [107, "吕布", "lvbu10", "DQkHDAgHDAkHDAgHDAkHDQkHDQkHDQkHDAkHCAYGCgcHCAYGCQgIDwwKDQkHDQkHDAgHCAYGCAUGBwYGDQsIFhMNEAwJDQkHDQkHDAgHCAYGCQcGFBELGhYPEw0LDQgHDAkIDQsKDAsLDAgHEg0JFBAMEQwLDggL"], [107, "吕布", "lvbu11", "DQkHDQkHDggGEwUEEgcFDgcGEQUEDQkHDAkHDAkGDwgFDwgGEAcFDwgHEAgGDQkHDQkHDQkHEwwEEAsFEgwJEwwJEw0JEgwFDQkHDgsJFRAJFxAEEw8MEwwLFQ8JFg8GEAsGEQ0IFhAKFA0FEQ4LDwoIEAsIFQ4F"], [107, "吕布", "lvbu12", "DQkHDAgHCQcGCQcHCwgICwkHDQkHDQkHDQkHCgcGBwUGCAcICAgJCQgICwgHDQkHDwsHDAkHCgcGCAcICQcHDw0KDQoIDQkHGBYJFxIIFhIIDAoJEAsIGBMMFhMNEhAOFxMHGhMHFBAKEQ8PGRcUGRYQFBENFhQS"], [107, "吕布", "lvbu13", "DQkHCwgHCAcGCQcHCwgICwgHDQkHDQkHDQkHCgcGBwYGBwcICAgJCQgICggHDQkHDgoKCwgHCAYGCAcICQcHEA0KDgsIDQkHEw4UCggJCAcICgkJEAsIGBMMFhMNExAODQkNCAcICAcJERAPGRcUGRYQFBENFxUS"], [107, "吕布", "lvbu14", "DQkHDAkHCAYGCAcGCwgICggIDAkHDQkHDQkHCggGBwYGBwcHCAgJCQgICggHDAkHDQoKDAkHCQcHCAcICAcHDgwKDwwJDAkHEA8UDAsLCgsKCwoKDgoIFxILGBQOFBEODQwOCwsKCgoLDw4OGBcUGRcRFRINFxUS"], [107, "吕布", "lvbu2", "DQkHDQkHDAgGDQkHDgoIDQkHDQkHDQkHDQkGDgkGDgYFEgYEEAcGCgcGDwoFDgoGDQkGDAgDEQgCDQQDDAMDCwUEDAgEDAkGDQgGDAUEEQkCDwcCCwMCDAQDCwUECgcGDQgHDQQDEAUDDgcCCgUDCwYFDQgHDQkH"], [107, "吕布", "lvbu3", "DQkHDQkGCwcFDAcFDQkHDQkHDQkHDQkHDQkGDggEDQYEEQcDDwkFDgsIDgoHDQkHDgkGEAkEDwgEEQkDEAwFFRELFA8JDQkHDgkFDwgFEgoDFw4BEgwEFg8HFgwEEQoEDggGDgUEFwwDGQ4DFg8GFgoGFgoFFw0E"], [107, "吕布", "lvbu4", "DQkHDQkHDQkHDQkHDAoGDAsGDQkHDQkHDQkHDwkGDwkHDQsGCwsGDgwIDQkHDQkHDAkHCwoLDQkHDQwIDAoGEw4JFREKDgoHDQoKCA8VBwoKCgsFDgwFFREKGhYNEAwIDQkICQ0QCAwOCQgECgoFDw0HEQ4IDQkH"], [107, "吕布", "lvbu5", "DQoHFA8JFxEIFA8HDgoHDQkHDQkHDQkHDwsIFhEKFhEKFxEJFhAHFBENDwsJDQkHDwwJEg4LEQ4KFg8HGhQIGxcSFxQQDgoHDwwJEAwJEw8KGRQNGRQMHBcPHBUJEw4IDwsJEQ0KGRQMGhUNGRUPGhQMGhUMGBIM"], [107, "吕布", "lvbu6", "DQkHEAoFEgoDEAkEDQkHDQkHDQkHDQkHDQkGDgkFDggEEAkEFA4GEQ4LDwsIDQkHDAgGCwcGCwcFFA0FGBEGGRUPFxQODgoHDAgGCwgGDwgEDwkFEg4IGxYNGxUJEAsGDAgGDAcFFQoCFAkDDQkGDgoGDwoGDwgE"], [107, "吕布", "lvbu7", "DQkHDQkHDAgGDAcFDAkHDQkHDQkHDwsHDQkHDQkHDAcFCwYEDAoIDgoIDAgHCwgGDQkHDAkHCgUECQYGEQ0KFRAKDgoHCwcGDQgHDgcFCgUECwgHEw4KGhQMEg0JDQoHDQkHDQcGCgYGDAgHFAwJFw0LFQwKCwkI"], [107, "吕布", "lvbu8", "DQkHDQkHDAkHDgkGEQoFDQkHDQkHDQkHDQkHEQkHEQgFEwoHEwkFEAkGDgkHDQkHDQkHEQoHFAgEFQkFEAgGEQ0KEQwIDQkHDQkHDQkHFAwEFQ0DEQ0HGBMMFxILDQkHDQkHDggGEwcCFQgCFg0FFxEJEgwGDQgG"], [107, "吕布", "lvbu9", "DQkHDQkHDQkHEAoGExANDgsJDQkHDQkHDQkHDAgGEAsIDwsIDgoIDQkHDAgGDQkHDQkGDQgFDQkIDQkHDgsHFA8KDgoHDQkHDQkHCwYFCgYFCwgGEg8IGhUNEAwIDAkHDAkHCwcFCwcGEAwLEAwKEg4KDgkHDQkH"], [310, "吕玲绮", "lvlingqi", "DQkHDwoIFAgHDAkJCggICwgHDQkHDQkHDQkHDwkIDAcGCAcIBwYHBwcICwgHDQkHDQkHDwgGCAYGDAoJFBALDwwJCggHDQkHDwgGFAcGCwYFEw8KHBYOFxELDAkHDQkHDQkHDggGDAgGEg0JGxUNFQ8KDQkHDQkH"], [221, "吕蒙", "lvmeng", "DQkHDAkHDAgGDAgGDgsIDwwKDQkHDQkHDQkHDAgGDAYECwgHERAPEA4NDQkHDQkHDQkHCwYECwYEDw0JFBQSFBYUDwwKDQkHDQkHCgUDCwUEEhANEhIPEREPDQkHDQkHDAkHCwYEDwgEFREMFBIPEAwKEQ0LEAwK"], [219, "马超", "machao", "DQkHDQoIEQ4MEA0LDQkIDQoIDQoIDQkHDQkHExAOFhMOExEODgwMDhAOEA8NDQkHDQkHFRMQEw8KFAwEEQwGEhMOFREODQoHDQoIFRMQEg4LEgwEEA8IFBMPGhUQEAwJDQkHExEOFBENEAwGEA8LGBQPHRcQEQwI"], [220, "马岱", "madai", "DQkHDQoIDgoHDAgHDQkHEQwFDQoHDQkHDQkHEQ4LEA0ICgcFDwoFFxEHDgsIDQkHDQkHEQ4LCwgGCwcFFQ8EGxYJEAwIDQkHDQkHDQkHCgcFDwoEFQ8FGhYLEAwIDQkHDQkHDQkHDQkHDQoIDQoIEw8KEAsIDQkH"], [314, "孟获", "menghuo", "DQkHDwkHDwoIDQkHDAkHDAkHDQkHDQkHDQkHEwoIFQ8NDQoKCwgHDQkGDQkHDQkHDgkHFQsJFQ4MCwgHDAoGDwsHDQkGDAgGDQkHEAgHEQoIDAcGCwgFDgoGDAcEDQcFDQkHDAgGEQgFEAgGCwYEDAYEDQYEDwcF"], [311, "潘凤", "panfeng", "DQkHDQkHDQkHDQoIEAwLDwoJDQkIDQkHDQkHDQkHDgoHDwsKEQ0MEg0NDwsKDQkHDAgIDAgJEQwHEg4KEw8MFBAQDgsKDAkHDAgJCgYKDwoHDgoHDwsKEg4ODgsKDAkHDAkHCwcICwYIDAcHDQgMEAsNDgoMDAkH"], [206, "庞统", "pangtong", "DQkHDQkHDQkHDQkGDAkGDAgHDAkHDQkHDQkHDQkHDQkFDAkGDg0KEQ8LDAkHDQkHDQkHDQkHDAgFDQoGExEIDQwJDQsHDQkHDQkHDAgGCwcFDAkHDQ0IDAwIDg0IDQkHDQkHDAgGCwgGDAoHCgkGDAsICwoGDAkH"], [101, "司马懿", "simayi", "DQkHDQkHDQkHDQkHDQoIEA4NDQoJDQkHDQkHDAYEDQgFDgkFDgsNExESEA0NDQkHDQgGCwUDCwUDDQYEDwwLExISDgsLDAgGDQkHDAgGDQgFDggIEQ8PFhcYExERDAgHDQkHDQkIDAgGDQgHEQ4QFxYXEQsIDQgG"], [101, "司马懿", "simayi11", "DQkHDgoHDgkGDggFDgoIDwwMDQoIDQkHDQkHDwkGDwoHEAwKDwwNEhESEQ8PDQkHDQkHDwsIDw4OEBAQEA0NExMVEhARDQoIDQkHDw0LDRITBRATDQ4QFRUXExISEQ4MDQkHFhMQGBkVDRcXCQ8SGBYUGRgVGBYS"], [101, "司马懿", "simayi2", "DQkHDQkHDQkHDgoIDgoHDQkHDQkHDQkHDQkHDQkHDQkGEQwKEg4MDwsJDQkGDQkHDQgGDwkEDwoIEQ8PFBEQEQ8RDQcFDAgGDgoIFA0DDwoEEQkGEg0KEQ8QDQoKCgoIDgsLEAoGDQcDDAUCEAgDDwgFCgsJCBEO"], [101, "司马懿", "simayi3", "DQkHDgoGEgsEDQkHDQoIDgoHEQwFDQkHDQkHDQkHDQgEDAgGDwwMDwsKDwkFDQkHDQkHDAgGDAcFDQwKEAwLEhARDgoJDQkHDQkHCwcGDQcEEQ4HFBAOEhESDAgHDQkHDQkHDAgHCwgIDg0OFBQXFBUWCwkIDQkH"], [101, "司马懿", "simayi4", "DQkHEQkDEQwFEg8HCwgJCgcIDQoJDQkHDAgHCwYFCwUGEAsHEA0NDgwOEA0ODgoHDAkHCwcHDwgEEAoHEhAREA4QExITEg0KDQkHDQkGEwwEEw0IEg8NEhETExEUDwkLDQkHDQkHDggGEAsIEg0MDgsOEA0SDgsO"], [101, "司马懿", "simayi5", "DAkHCAgKCgkJCwcHDAgKEA0NDQkHDQkHCwgIBwcLCgkLCwcKDAgLERARDw0MDQkHCwgHCgUHDAYHDAgKDwwOExITDgsKDQkHDQkHDAcGCgUFDQkIEQ8QEhIUDwsLDgsJDQkJDwwKEg8NCwcIDw0QFhcYFhUSEQ8M"], [101, "司马懿", "simayi7", "DQkHDQkHDAkHDAkIDAkIDgwLDQkHDQkHDAkHCwcGCQkJCQoKCgcIEQ8QDwwLDQkHCwcGCgUFCwgHCQcHDQoJEhESDgsLDAkHDAkHCwcGCQUECgYHEQ8PFRUXEA4ODAgHDQkHDQkICwcGDw0MExIUFhcZFBMSDgoI"], [101, "司马懿", "simayi8", "DQkHEw8MGRUTFRANDgkIDQkHDQkHDQkHDgkHFg0EGREHFw8IEAkJDwsJDQkHDQoIDQkHEAgGEwkFFxAMFxESFhEOEQ0KDgsJDQkHEAoHGBIKGhMRGhQTGxYSFxEKDQoHDQkHDgoHFRAKGRMNFxAMGRILFxAIEg4J"], [101, "司马懿", "simayi9", "DQkHDQkHDQcFDgUCEwgFEw0IEQwIDgoHDQkHDQYEEAYEEwkEEwsFGBEIFg4HEAwIDAkHCwQDDAQCEgoEFBAHFRINFREKDwsIDQoHDwcEEQcEEwoEFA8FFBAJFBAJEQoFCgsNDAkHEAkDEwsDEwwEDwwICgoKDwkF"], [111, "孙策", "sunce", "DQkHDAgGDAcGDAgGDQkHDgoIDQkHDQkHDQkHDAcFDQUDDAUDDQcFEgwKDQkHDQkHDQkHCwYECwQCDAUDEgsFFxENEAwKDQkHDAkHCwUEDAUCEgsFGBELGRQREQwKDgkFDAkHEAgDFQsBFAsCFg4KEgsJDQYEEQkD"], [111, "孙策", "sunce2", "DQkHDQkHDQkHDAoJDAkJDQkHDQkHDQkHDQkHDQkHDAgHDQYGEAcHEQcFDQkGDQkHCgoKDQYFDQUFCwUFDgQFEggEFQoEEggGCAkKDQYDEwgDEwcGCwYHCgkLFAkEEgoFEAwFEQsCFQwCEgkEEwsIEAsKDgUEEQcG"], [111, "孙策", "sunce3", "DQkHDAgGDQgGDAcGCwYFDAgGDQkHDQkHDAkHCwYFDgUFDwQFDQQFDwkIDQkHDQkHDAkHCQYFCQQEDQQEEwoGFQ8MDgoIDQkHDAkHCwcGDgkFEAoIFxEMGBIQDQgHDAkHCwgGCwUDEQsDEAoFEQcHEQUHDQQEDAgG"], [111, "孙策", "sunce4", "DQkHDQkHDAgGDAgGDQkHDgoIDQkHDQkHDQkHDAgGCwUDDgYEEQkHEgwKDQkHDQkHDQkHDQcEDQUDFAsJFQ0HFxANEAsJDQkHDgkFDAUDDAUDEgsHGBIMGRQQDwoIDQkHDAkHCwYEEwgGGA4LGBAMEwwJDQYFEQoI"], [111, "孙策", "sunce5", "DQkHCwYFDQcFDQgGCwYFDQoIDAkHDQkHDQkHDQgHEQgFDQcEDwgFEAoICwYFDQkHDQkHDAcHCwUEDQcEFQ4IFxIPDAgGDQkHDQkHDgkHCwYFEQsJFhEOFA4MDAcGDAkHEgoGFw0HEQoHEQoHEQkIDgkICgYFCQYF"], [111, "孙策", "sunce6", "DQkHDAkHCwoKCwsMDgsKDgoIDQkHDQkHDAkHCQsLDQ8LEhANDQgGEgwJDgkHDQkHDAkIBwwNFRIJFBEOEAkEFQ4JEg0KDQkHDAkHCgoKEg0LEQ4LEg0HEw4KEQ4MDgsJDQkHEQ4NFxUTFhIOEg0MEQ4NDw0MDg0L"], [111, "孙策", "sunce7", "DQkHDAkHDAkHDAgHDAgHDgYEDggGDQkHDAkHCQcFCwkIDAgHDAcFEAoIDgoIDQkHDQkHCwgHCwcGCwYFDwgFFQ4LEQwKDQkHDQkHDQoJCwYFDAYFEg0HGBIPEg0LCwgGDQgGDQkHCwcGCwcGCw0KEQ0KDQcGCgcF"], [111, "孙策", "sunce8", "DQkHDQkHDgkHEAkGEQgGDwgGDQkHDQkHDgkHDQkHEQkGFQgEFAYEDwcFDQkHDQkHEgoGEwoFFgsFFw0GEAYFDQYFEAkGDQkHDgkHEwkFFA0LERAQDggIEQgFFgwFDwsIDwsHFQ4JEg0OEAoKCgcIEgoHEgoGDQkJ"], [115, "孙坚", "sunjian", "DQkHEQ4LEw4MDgkGDgoHEAsIDQkHDQkHDQkHFBIPEQ0KEQkCEQoFEw4KDgoIDQkHDQkHExEOEQoFEwsEEgsGGRMQDwsJDQkHDQkHEQwHFAwDFAsEDgcEDwkHDAcEDQgGDQkGEAwIEg8LEAkDDQYCDAQCDgYCDggD"], [115, "孙坚", "sunjian2", "DQkHDQkHDQkHDQkHDQkHDgoGDQkHDQkHDQkHDQkHDQoIEQ4MFBALEwsDDQkGDQkHDwsIDwoFEAwIDQsJEw0GEgsCDgcDDQkGEQwHEwoCFAsBDQcDEgsDEwwIEAQDDgcEEQsGEwoCEAkCDwcCDQcDDQgGDgYDDwgE"], [115, "孙坚", "sunjian3", "DQkHDgsJFxYSGBYTEAwJDwoIDQkHDQkHDQkHExANGhoWFhQQEgwIEw0KDQkHDQkHDQkHEhANFhUSEw4JEgsHGRQQDgoIDQkHDQkHDgsJEg8MFQ0KDwkGEAoIDQcFDgoHDQkHDwwKFhQRFA4MEw8MDgcGDwgHDwoI"], [115, "孙坚", "sunjian4", "DQkHDQkHDQkHDQkHDQkHEAsIDQkHDQkHDQkHDAkHCwkIDAgHDwgFEw0KDwsIDQkHDAkHCggICQkJDgkGEQoEGBIOEg4MDQkHCwkICQkKCQsMDQsMEQoHEAoIDggGDAcFCQgICAkKCQsMCQoLDAgHCwUECgQDCQYF"], [115, "孙坚", "sunjian5", "DQkHDQkHDgcEEAoEEQsFDgoIDQoHDQkHDQkHDQYFDwMBFAoCFAwEEgwIDwsJDQkHDQgGDwQCEAMAEwkCEAgCEw0JFRAODAcFDAgGDwMCEAMBDgcDCQUEDAcFDQgGBwQDDQgGDwUDEgoEEAsECAQEDAoJCwcHCAUE"], [115, "孙坚", "sunjian6", "DQkHDAkHDAkHCwcGDQkHDwsIDQkHDQkHCgcGCAUFCAYFCQYEEAsIFA8MDAkHDQkHCQYFBwUFBwUFDQgFDAkHEQ4NCQcGCggGDAkHDAcGDgcFDggHBwUFBwUFBwUEDAcFDAkIDAUDFAkFEwwIDAcGDgsHCwcGEAcE"], [106, "太史慈", "taishici", "DQkHDgsIDwsJDgkHDQkHDAcGDQkHDQkHDQoIFBIPEwwJEQkGDQgGDAcHDwoIDQkHDQoIFBIPEgsJDwgFDgoGDgkGEQsJDQkHDQkHDwwJEg0KEAcDEAkFDwkGEgsIDgoGDQkHDQoIDwkFEggCEwkEEwsHEwgFEAoG"], [106, "太史慈", "taishici2", "DQkHDQkHDQkHDgsIDwwKDQoIDQkHDQkHDQkHDQkHDQoIExENFhQQEg8NDQoHDQkHDQkHDgkGEQsIFQwIFgwIFg0JEgwFDwoGDQkGDwcDFQwCEwgFEgcLFwkMFgkEEAoFDQgGDwcDFAwBEgoCDAQLDAQIEAYFDggG"], [106, "太史慈", "taishici3", "DQkHDQkHEA0KEQ0LDAcHDQgHDQkHDQkHDQkHDwwKGBcTEhAOCwYHDwkIDgkHDQkHDQkHExAOFxYTEA0KDgoGDwoJDwoIDQkHDQkHEQ4LFxUSEQ4MDAgHEQsKEgwKDQkIDQkHDQoIEA0LEAwKExAOFhMQFREODgoI"], [106, "太史慈", "taishici4", "DQkHDQkHDwwKEQ0LDgoIDAgHDQkHDQkHDQkHDQoIFRIPFA0MDQYHDQcHDwkIDQkHDQkHDwwJFBIPEw0LEAsHDggHEAoJDQkHDQkHDgoIEQwKEQ4MDAcGDggIEgsKDQkHDQkHDQgGDgcFDAcGBwQFCQYGCwcGCwcG"], [106, "太史慈", "taishici5", "DQkHDQkHDAkHCwYFDQYFDQcGDQkHDQkHDQkHDQkHDQgGCQQFCQQGDggHDQkHDQkHDAkHDgcGDgYEBgEFCgUFDwkIDgkIDQkHDQkHDQgGDQMDBwIFDAgFEAoJEwkIDwgHDQkHCwcGBgIFDgQEEgUFFQgHGAcGEgkG"], [106, "太史慈", "taishici6", "DQkHDQkHDQkHDQkHDQgHFA0IEw8NDQoJDQkGDQgFDgsJDwwKDAcHEAoJFg0HEwoFDQkGDgkFEQ0JEQwIDgkGEQoJGQ4GGA0FDQkHEgsGFg8GDAgGCwcGEQsKEAkGEwoFDQkHFAwFFw8FEQsHCggIDQkJDQkHEQ0L"], [106, "太史慈", "taishici7", "DwoHGA0EEwcGDgkHEQgFEwkEFAsFDQkHDwkGFw0EDwgIEAkKEQgDEQkEFAoDDgkGDQkHEwoEEQkKEgoKEgkCFAoDEQcDDgkFDQkHEAkGEwkDFQsFFAsKFAsMEgkFDgkFDQkJEQkJEQgLDgYDEAcGFAsREQgJDAcG"], [217, "魏延", "weiyan", "DQkHDQgGDQcEDQcEDAgGDQoHDQkHDQkHDQkHDQgFDAYDCwUDDwkFFQ4HDwoGDQkHDQkHDAcEDAUDEQkCGRAGGhIIEwwFDQkHDAgGCwYEDQYDFw8EGxMIGhMJFw8EDgkFDAcFCwYDDAgDEwwGGBEIGBEHFg8FDwoG"], [228, "文丑", "wenchou", "DQkHDQkHDQkHDAkHDQoIDgoJDQkHDQkHDQkHDQkHDAkHCwkHDgwJEg4MDgoIDQkHDQkHDQkGDwkEDQgEDw0HFhMOEA0LDQkGDQkHDggFEQkDDQoHEA4HFhQNFBANEAkDDAgHDQgFDgYIDQYOEQoFFAwFEQsGDQgG"], [214, "夏侯惇", "xiahoudun", "DQkHDAkIDAkIDQkIDQkHDQkIDQkHDQkHDQkHCwkJCgkKCwcHDAcIDQkKDQkHDQkHDQkHCwgHCgUGCwYHCwYIDQgLDAkHDQkHDQkHDAcGCgUHDQcHCwYHDAYGDAcGDQkHDQkHCggICgsNCgcJCQUGCgUFCwcGDAkH"], [216, "夏侯渊", "xiahouyuan", "DQkHDQkHDAkIDQkIDQkIDQkIDQkHDQkHDQkHDgsMCQoNDAoLDQkLDwoODQkIDQkHDQkHDgwOBwoNDAgLEAsLEw4TEAsLDQkHDQkHDQkJCggJDAkLDgkNDwoNCwcIDAgHDQkHDAkIDgwNDwwKCwkKCwkKCAcICwgH"], [224, "小乔", "xiaoqiao", "DQkHDQkHDQcGDQYHDgUHDQYHDQcGDQkHDQkHDQkHEAkEDgUHDgQHDgQHDwgFDQkHDQkHDQcHDgUGEgkJEwsKEwoJDwYHDQgHEQ0HEgsFDgUEEwsKHBYPGRINDgcHDQgHFhEFGhICEwgDEAkGGhUOFg8LDgcGDQkH"], [312, "邢道荣", "xingdaorong", "DQkHCwkHCggGDAgGDAkGDAgGDQkHDQkHDQkHCAgGDAkFDQsGCwoGCwkGDAgGDQkHDQkHCQcFDAkEDQkEDQoGDgsHDAcFDAgGDQkHCwgFDAgECwcECwUEDAYECwUEDAgGDQkHDAgGDQgECwYICQQJCQQGCgUGDAgH"], [215, "许褚", "xuchu", "DQkHDAgGDAgFDAgGDAkIDAkIDQkHDQkHDQkHDAcECwYDCwgGCwwNEhAMEQ4KDQkHDQkHDAkHCgcFCwgFDw8KGBYPGxkRDwsJDQkHDAkHDAgHCgkIDQ4MGBUOHRoREQ4KDQkHCgkIDAkIDQoKDQwMFBENFhMPEA0M"], [201, "徐晃", "xuhuang", "DQkHDAkHCgkKCAoMCwoLDQoIDQoHDQkHDQkHCggHBQkMBg0SDg0MEg8NEA0KDQkHDQkHCggHBwgKCwsMEA0IExALEQ4LDQkHDQkHCgcHCAcICgkJEQ4JExEMFhUSDgoIDQkHDQkHCQgJCAcICwoKDQ8QExIRDAoJ"], [202, "荀彧", "xunyu", "DQkHDwsHEAoHEQsDEAsHDwsJDQkHDQkHDQkHDgoHDwkGEAwIFRAOFg8MDwoHDQkHDQkHCwcFCwUEExAIGhcSGhYPFREMDQkHDQkHDAgGCwYEEAwJGBYSGxcRFxIMDgkGDQkHDQkHCwcGCwgGDwsJFhEMEQwIDQgG"], [302, "许攸", "xuyou", "DQkHDAkHDAkIDQkHDgoJDwsMDQoIDQkHDAkHCggICgkJDAoJEQ4PEg4REAwMDQkHDAkHCggICQkJDAsLExAMFhMUEg4ODAkHDAkHDAgHCwgIDAoLExARFRITDwsLDAkHDQkHDQkHDAkHCwgJDgoMEA0ODwsLDQkH"], [227, "颜良", "yanliang", "DQkHDQgHDQgFDQgFDQkGDwsKDQkHDQkHDAkHDQUEDgYBEAkBDgkIFRAODwsJDQkHDQkHDAQDDwYDEQkDEAwJEw8NEgkGDQgGDQkHDAYFDAYHEAgHDwsIDwgIDwYFDQgHDQkHDAkIDQgHEwoCDwcGDgYKDwgGDQkH"], [225, "袁绍", "yuanshao", "DQkHDgsJFhIOEgwHDgoIDQkGDQkHDQkHDQkHDwwKFREMFhMPEg4KEAoGDQkGDQkHDQkHDwwKFRMQFhMOEQwHEw4LEQ4LDQkHDQkHDwwJFRMQFxUREw8MFRIOFRMPDQkIDQkHDQoIDgsIEQ0JDgsKFBIPEhEPCwkJ"], [303, "于禁", "yujin", "DQkHDAkHDAkJDQkIDAkIDgwMDQkHDQkHDAkHCwoKCQsNCwcIDQsMDxARDQoIDQkHDQkHCwgHCAgJDAkJEA4MEBISEA4LDQoHDQkHDAkHDAgGDgoIEhANFRcVGhcSDwsIDQkHCwgICgkJCgoNDwsMFRUSGhkUDgsJ"], [204, "张飞", "zhangfei", "DQkHDQkHDAkHDQkHDgsJDQoIDQkHDQkHDQkHDAkHCgYFCgcFCggHDgsJDAgGDAkHDQkHCwcGCQQECQQDCwgEDAkHCgYGCwcGDQkHDAkHCgUECgQDCQYFCgYFCAQFCgYFDQkHCwgHDAcEEAcCCgUECgUECQYEDAgH"], [120, "张角", "zhangjiao", "DQkHDAgGDQgGDgkGDAgGDAgGDQkHDQkHDQkHDAYFEQoGDwkFCgYFDQgGDQkHDQkHDQkHDAgGDggFDAgEDQoGFBIODQoHDQkHDQkHDQgGDAYFDAcGEg0JGBcRDgsIDQkGDQkHDQcFDQYDCgYGEQsHFA8JDAgGDggF"], [120, "张角", "zhangjiao2", "DQkHCwYFCwYGDQkHDQkHDAgHDAkHDQkHDQkHCwcFDAYFEA0IDgoGDAcGDQgHDQkHDQkHDAgHDQgHDggGDAgEDwwJEQ4LDgkHDQkHDQgHDwoHEAsIDgkHEAsLEw8ODgkHDQkHDgcGEgwHEg0IEAsIEgwKEw0KDgoH"], [120, "张角", "zhangjiao3", "DQkHDQoHDQkHDQkGEAoEDQkGDQkGDQkHDgkFEg4GDwsHEAkKFQsEEgkFDwgEEAsGDQkGDwkFEw4IFQ0JFQwFEwsIEQoDEgwFDwkFEgsKFAwIEwwDFg4EEwwDEQsDEAsFDQkHEAkHEwoIEgkFEwsHDwkEEgkFDgkG"], [120, "张角", "zhangjiao4", "CwgHCAUJCwkMBwcNCQYICAQHCwcHDQkHCwcHCgYGCgUHCAUKCAUHCwcHDQkHDQkHDQkHCgcHCAUKDgsLDQoHEhANFBIPDwoJDAkHCgYICwgLEg8NEQ0LGBYTGxoXFREQDQkHDQgHDwoKEAwPDwoNFhIRGhgUExAO"], [120, "张角", "zhangjiao5", "DgsJFBIRDwwJDQkHDQkHDQkHDQkHDQkHDQoIDwwLEQ4KDQoHDAkHDgsJDQkHDQkHDAgHCwcHDAgHDQoHDwsJFhQRDQkIDQkHDQkHDAsJDAwNDQkMEQ0NGBcUDgwLDAkIDQkIDQoNDA0QDA4PDxARFRUUDQ0PCw0Q"], [120, "张角", "zhangjiao6", "DQkHEAwIEAwLDggQDgUXDgkMEAwKDQkHDQkHEAsKFRIPEgwSDgQVEQsREQwODgoHDgkFEgsREAkSEQwIEgwMEw4KFBAQEw8JDQgDFhINFhMVEQ0OEAsMEgwIFhQQEQwHDwoGEgsGExAIFBEMEAgPEAgNEw4IEAoG"], [120, "张角", "zhangjiao7", "DgoIDwwKExEOGhkWFhQRDwwJDQkHDQkHEQ4LGBcUGhkVFhURDgsIEQ0LDgoJDQkHDQoHEA0LFRMQDwwIEA0KExAODwwNDgsKDAgHDgoIDgoKDwsIFBEPFBEUEg8UDgsMCwcJDAcKEAsKEQsHEg0KExAPEAwMCwcJ"], [120, "张角", "zhangjiao8", "DQkHDAoICwsKDgwLEA0KDAgHDQkHDQkHDAkHCgsJDxEPERAODgoJCwgGDAwKDAoIDAgGCgcGDAoICwgGDAoHDAoIDQ8ODA4MDA0LCwoJCAcGCQcGEhENEhEOEA8MDg8OCgwLDAwLCgwKDQ4NEBEPDhAPDQ0MEQ8P"], [213, "张辽", "zhangliao", "DQkHDAkHDQkLDQkLDQkHDAkHDQkHDQkHDQkHDAgJDQoPDgoMCwcHDAgIDQkIDQkHDQkHDAgLDQoKDwoICwcGDQoKEAsKDQkHDQkHCwgKCwgICwgGDAkHDwsLEg0LDQkHDAkHCwcJCwcHCwkIDgoIEg4NEQwLDAkH"], [304, "张星彩", "zhangxingcai", "DQkHDQkHDAkHCgcGCgcGDAgHDQkHDQkHDQkHDAkHCgcGBwYGCAYHCQYHDAgHDQkHDQkHDAgHCggICwkJCgcHCgcHCwgHDQkHDQkHDAgHCQYFFA4JFxELFA0JDAgHDQkHDQkHDgkFDQcEEgwIGhMNFA4KDQkHDQkH"], [308, "张昭", "zhangzhao", "DQkHDAgHCwcGDAgGDQgGEQwJDQkHDQkHDQkHCwcGCgUEDQgFDgcHEAkIDgkHDQkHDQkHDQYECwUDDggFEAoGFBAKFBALDQoHDQkHDgcFDgkGDwkHEQsHGBUNGhcPEAwIDQkHDgcFCwcFDAcFDwoGFBAKFhMMDQkH"], [118, "赵云", "zhaoyun", "DQkHCwgHCgcHCwcHDAgHEQsIDQkHDQkHDQkHCwYGCQYHCwcIEQsKFw4LEAsIDQkHDQkHCwcGCQUGDgkIFxEJGhQPFhMPDQkHDQkHDAgHCgYFDwkIGxMNHRkUGRcTDQoIDQkHDQkHDAkICwoLDg0NFhYUEhMSDAkI"], [118, "赵云", "zhaoyun2", "DQkHExAOGhgUExIQDg4QEAwKEgwJDQkHDQkIFhQRGBcUEQ8NEQ8OFA4LGBENEAsJDQoIFRQRFRQREA4MEg8MFxEKHRkUFRIPDQoIEA0LEQ4MEg8NEhEPFBIOHBoWFhUTDQkHDQkHExAOFhQSFBIQEBAQDhEXDxAT"], [118, "赵云", "zhaoyun3", "DQkHDQkHDQkHDQ4NExIQDgwKDAoIDQkHDQkHDQkHEQ4LFRUTFBgWFRQPDA0KDQkHDQkHDgsIFBEOGBYSExgWERURDA8NDQkHDAsJDRAPFBMQEhAMEBERDhITDQ8PDQwJDQoJDw4MFRMODQwKDA0QCwwPEQ4LDwwJ"], [118, "赵云", "zhaoyun4", "DQkHDQoKDwwPEhARDw0MDwsIDQkHDQkHDAkKDw4QDxIYFBYYFxQSFg8MDwoIDQkHDQoNDg8WEBEVEA8QFRALHBYSExAODgsKEA0MERETEBASFBITGRYSHBoWGBcWERETEg8OEhITDw8REBETFRUXFRUWEhIUDAsM"], [118, "赵云", "zhaoyun5", "DQkIDQkLDwoIEQsMEQsMDwoODQkIDQkHDAkIDgoVDwoXEQsOEwwKFA0LEQwLDQkIDAkKDAgTDgkXEw4WFA4RFw8LFxAODgoJDAgMCwcSCwcQDggKEw0LGhMNGxgUDgsJDQkHDAgJCAUJCAUJDAgIFA4KGRQNDwkH"], [118, "赵云", "zhaoyun6", "DQkHEQ8NFhQRFhYVEhITDgwODwoJDQkHDQoIEhAOEg8NCwsRCg0TDAwPFQ4MEQwJDAsLEBEREA4NBwkQCA0UEA4MGxUPFxUSCw0ODhATDQ4SCQ0RCxIWDhISGBYSGRgVCgoKDRASDhEVEBMVFBsZFBcVFBMRFRAQ"], [118, "赵云", "zhaoyun7", "Eg8MGBcUGhkVERQRCw4KDwsJDQkHDQkHFA0FFhQOEA8KCw4KDQ0KFxAMEQwIDQkHEQwHFQ0EEgwEEA0HEw8IHBYRFRQQDg4JEwwGEwsEEA4IDhALEA8JHBgSFxYSDQ8LEgkDFQoBEQ8HCxAMDQ4KFBAJEQ8JDA0J"], [118, "赵云", "zhaoyun8", "DQkHEhIPFxwXDhERExQSDw4OCwoKDQkHDQkHDxANERgVCg8PCw0ODxIPCgwKDQkHDAkICgwNCQ4RDRAQDQ0NEhMQDQ4LDAkHDg0MCgwNDw8PEQ8ODQwNDg8PDw8OCgoJDAsMCwoLDwwMDgwMDw0NDA4PEREQEA4N"], [118, "赵云", "zhaoyun9", "FBAIFBAJFg8IGRILFhEKDwsIDQkHDQkHGRMIFhAIHBUJHhgLHRgPGBINDwwIDQkHFxMKHBYKHhYIHBUJGhQKHBgRFxMMEg0GFhEJHBYKHRUGHBMFGxcNHBoUGhcRFg8HDwwIHBgOGxIGGg8BGRIFGRULGBMMFBAL"], [109, "甄姬", "zhenji", "DQkHCwcIBgULBgULCwcHDAgGDAgJDQkHDQkHDAkHCAUJBQYMCAgLCAgKDAkIDQkHDQkHDAgHBwUKBwkNFhIPDw0MCggIDQkHDQkHDAkHCwgLEg8MHBcQFBAMDAgHDQkHDQkHDQkHERAOFRIPGRQPEg8NDQoIDQkH"], [109, "甄姬", "zhenji2", "DQkHDQkHDQkHCwkJBggMBwgLDAkIDQkHDQkHDQkHDQkHDQkKCgkKCQgLDgoHDQkHDQkIDQkHEAsMEQ4PDQ0OFRMLEg4IDQkHFAwQEQsOEg8TExMVDA8QEBQUEhIQDg8OFAwRDQ4TDxEPEhYVERISDAoOERESDw4M"], [109, "甄姬", "zhenji3", "DQkHCggIBgULDg0OEREQEREPDQoIDQkHDQkHCQcJBgYMCQkNCgkNCAkMDAkIDQkHDAkHCAUJBwQKCAgNFhIODAsNCQgJDQkHDQkHCAYKBgQKDgwMHBcQEQ8MCwgIDQkHDQkHCQcJBgULDgoKGhYQEg4LDAkHDQkH"], [109, "甄姬", "zhenji4", "CwgICQUICQYIDgoGDAwKDAkHDQkHDQkHDQkHCwgICAUJCgkKDw0KCgkLDAkIDQkHDQkHDAkHCAYKBggNFRIQEA8OCwgIDQkHDQkHDAkHCgcJDQoMGhcSFxQQDQoIDQkHDQkHDAkHDAkIEQ0NGBMPFBAOEAwMDQkH"], [109, "甄姬", "zhenji5", "DQkHDQoIEA8PERERERERERAQDQoIDQkHDQkIDgwMEBAREhMUEBESEBARDQoJDQkHDQkHDQoJDg0PDg0PERARDgwNDQoIDQkHDQkHDQkIDAkKExAOGxcSEQ4MDAkIDQkHDQkHDAkHDAoLEw8NGhUQDw0OCwkIDQkH"], [109, "甄姬", "zhenji7", "DQkHDQkHDAgGDQoKCggIDAgGDQkHDQkHDQkHDAkHCgYGDAsLCgcHCgYFDAkHDQkHDQkHDAkHCAUFCAYHEQwKFA8LDAgHDQkHDQkHCwcGCgYGCwcHFxIOGBMOCwcGDAkHCwcGBwkKBwkKCgYGFRAMFA8LCgYGDAgH"], [109, "甄姬", "zhenji8", "DQkHDAcGDwoHEgsHDgcFDQgHDQkHDQkHDQkHDgkGEAkFEAcGDwYGDgYFDQgHDQkHDQkHDAcFDQUEDQYFFQ8NFA8MDQgHDQkHDAgHCgQECgQEDwkIGxgTFREODgkJDwoJDQkMDAcMCwQEEQwKHRkUFBAODwoJDQgH"], [109, "甄姬", "zhenji9", "DQkHDw0LCAoNBQYLAwMJBwgMDAoIDQkHDQkHDQgHEAsJCAkMBAULDQwQCwgIDQkHCQkKCQcJDQkJEAwJDA0OGBcUDg0NDQkHBAsQDA8NDRYVDw4MEhAPGRYTDxAPDxUSBQ4TDhMSDRoZDA4OEAoIEQwJDg0LDhgX"], [301, "周泰", "zhoutai", "DQkHDQkHDQkHDQkHDQoIDgsJDQkHDQkHDQkHDQkHDgoHDgoIEQ8MEA8MDwwJDQkHDggGEAkFEg4GDgsIEg8JFRIOEw8NDQkHDQgGDwYEDwoEDgoHEg0JFhEOEg0MDQkHDQkHDQcGDQYFDQcEEAgGFQ8MEgwKDQkH"], [105, "周瑜", "zhouyu", "DQkHDQkHDAgHCgcGDQkIEAwLDgoJDQkHDQkHDQkHCgcGDQkJEQ4OGRcXEQ4MDQkHDQkHDAkHCgcHDwwJFhQSHRwcFhQTDQkHDQkHDAgHCQYGEQwKGBYVHRwcFxUVDQkHDAkHCgcGCAUFEQcGFQ8PFREREQsLDgkH"], [105, "周瑜", "zhouyu2", "DQkHDQkHDQkIDQkIDQkIDQoIDQkHDQkHDQkHDQkIDggHDwkIDwoJDgoJDQoIDQkHDgoHEA4MDwsLDgYFDwgHEAoJDgoJEAwHDwoHFA8JFBIOExAQEg0JDwoHDgsKEQ0IEAsKEg4NDw0LEAoIEggGFhEJEg4LDgsJ"], [105, "周瑜", "zhouyu3", "DQkHDAkHCwoJCgkJCQcGDgkIDgoIDQkHDQkHDAkHCQgICQcIDgsKFBAPEA0MDQkHDQkHDAkHCQUFDQoIExEMGhkYExEPDQkHDQkHCwcGCQYGDwwIFBELGRgWEhAODQkHDQgGDQUEDQkFCgwLEw4HFBENDw0NDAkH"], [105, "周瑜", "zhouyu4", "DQkGDQgEDQgGDwsKEA0MDgkIDQkHDQkHDQkHDwoDDggGFRISExAQExAQDgsJDQkHDQkHEAoEEw8OFhQTFBIPGBcXEQ4MDQkHDQkHDQkHEQ4MEw8LFhMNHBsZExANDQkHDQkHDQkHDgkFDwoEEAsFFg8GFAwEDgoF"], [105, "周瑜", "zhouyu5", "DQkHDQkHDQkGCgcGCwgHDwoIDQkIDQkHDQkHDgoHCQcFCAYGDQsLFBISEQ4MDQkHEgwHGA8HEAoGDQoJEg8OGhkZGRMOFA0HGhEHGhIHGhIHEQwKEQ8PFxcXFhIOGhIIGBEIEQ0JEQwHFhMREA4PCAYGDgwMEw8N"], [105, "周瑜", "zhouyu6", "DQkHDAkHCwgHCwcGCQYGDQgHDQkHDQkHDQkHCgcGCQcGCQYGDgsLEg8ODQoIDQkHDAkHCQUFCAQECQcGEQ8OFxUVDgoIDQkHDQkHCgcGCAUEDQoFFhQTGxoZDgoIDQkHDQkHCgcGBwUFDQkFExAOFhQSDQkHDQkH"], [105, "周瑜", "zhouyu7", "DQkHDQkHDAoIDgoJEAwLDAgGDAgGDQkHDQkHCwgICwoLExAQFRIREg4NDgkIDQkHDAcGCwcGDwwLFhMSFBEOGBYWEQ0NDAgHDAUEDQYFDQgGCwgGDwwJGhkYExEQDAgHEAcEDgYFEggEEQkFDgkGDgsKDwoJEAgF"], [105, "周瑜", "zhouyu8", "DQkHDQoIEAwKEQsIEAoIDQoIDQgHDQkHDQkHDQoIEw4LGBANFQ0LEg0LDggGDQkHDgoIDgoIEgoIFg0LEw4MFhAODwkHDgoIEAwKFQ0KFQoIFhEOGRQOGRIOFAwKDgoIDgsIFw8LFQ0KFQ0LFgsJGBANGBEOEg4L"], [105, "周瑜", "zhouyu9", "DQoHEAwGDwoGEQwIEQwKDwoHDQkHDQkHDQkHEgwGFQ4GGBMNFxALFhENDgoIDQkHDQkHEQwFGBIMGRQLGxUHHBgTEQ0KDQkHDQkHEQ0HFhAKGRMKGxYLHRkSFBALDQkHDgoHFxEIGxQHGhMIGBIJFw4GFg0GEAsG"], [104, "诸葛亮", "zhugeliang", "DQkHDQkHDgoJDQkIDwsHDwsIDQoHDQkHDQkHDgsJFBISEQ0JEgsGEgwHDgoHDQkHDQkHDwsJEA4LDwkGEw0EFAwGDggGDQkHDQkHDQgFDQkGDQYDFAwEGA8IDwgGDAgHDQkGDggDDQgGDgkGDwoGDwoFDAcFDQkH"], [104, "诸葛亮", "zhugeliang2", "DQkHDQkHDQkGDQoHDQkHDgkGDQkHDQkHDQkHDQkHEAoFFA0FExEOEw8MDgoHDQkHDQoIEhAOFRALEwsFFhEGFxEHEg4JDgoIDwwKExEOEAsIEAoGExAHFQ8HEAoEDQgGEQsGEQ0LDQgFEQoDDw4HERAMEQsGDQoI"], [104, "诸葛亮", "zhugeliang3", "DQkHDQkHDgkHDAgHDQgGDwsIDQkHDQkHDQkHDQkHEwsKDQcIEAoFEw0IDwoIDQkHDQkHDAgHDwgIDQcGEw0EFA0HDwoIDQkHEw0EEQwEDgkHDgkJFw8GGhEJEg0LDQkHEQ4FEQwDEAsIEg4LFhAKGRMOEQ4MDQkH"], [104, "诸葛亮", "zhugeliang4", "DQkHDwgHFAsHEQkGDQgGDgoHDQkHDQkHDwYFEggGFg4IFQoEEQgEEw0HEAsIDQkHDQgHFAoHFQ0GEggEEgsEFA0GEQsIDAkHDQkHEAcFEgcEEQgGFw8HGhEIFA4KDAgHDQkHDQgGDQYFEQ0MFRAMGBELEwwKDAcH"], [104, "诸葛亮", "zhugeliang5", "DQkHDQkHDwwJGBYTHBsYGhgVEA0KDQkHDQkHDgsJGBURGRYQGRUQGRUQFhMPDQoIDQkHEAwKGhcSGRUMEw0EFA0HFxIMEAwJDQkHDwsIFxIMFA4HFA0EFg8HEw0JDQkHDQkHDQkHEAwHFA8FFxAGGhMIFhEKDQkH"], [104, "诸葛亮", "zhugeliang6", "DQkHEAoFDwsIExENEg4JDwsIDQkHDQkHDwsIFQ8HFA8HFREMFxAIEw8JDQkHDQkHEA0KExALEQ0IFBAIGBIIGRMNEAwKDQkHDQoIDgoIDgoHEw8JFxQOGBUQGBcTDwwKDQkHDQgGDggGDwkGFBAMFRIOGxoVEg8M"], [104, "诸葛亮", "zhugeliang7", "DQkHCwoJCwsJDAkIDAkHDQkHDQkHDQkHDAkHCQoJCgsJDAoIDwoGEg0JDQkHDQkHDAgHCgcGCQgHDAgGEwwGFQ8KDgoIDQkHDAgHCwcGCggGDQoFFA4FFhALDgoIDQkHDAkHDQkGCwwJCwwJFw8IHBQNFBENDQoI"], [104, "诸葛亮", "zhugeliang8", "DQkHDQkHDQgGEQ4MFhYVExEQDQkHDQkHDQkHDQgHDwgFEAoHExEOEg0LDggGDgoIDwkHDgoIDggGEAcFEgkFDwkFDwgGDgsJEQoIEQwJEAoGDwkHEAwGDwsFDgkHDQoIDw0MEQwIEgsGEAsIEQ8IExUJDw0IDgwK"], [104, "诸葛亮", "zhugeliang9", "DAoIEQ8OFhAOEw4MDQkHDgoHDQkHDQkHCwoJCBIRDRAQEAsKEwwGEgwIDQkHDQkHDAoIBxEQBw0MDQsIEgwFEgwICgcHDAgHDQkHCwkHCQcHDgwNFA4MGBALDQsLDQoJDQkHDwwLEw8QEQ4PEQoKFQgHEw8QFhMU"], [0, "非武将头像", "zhugong", "DAkHCwgHCgcHCwcIDAkJDAkJDAkHDQkHDAkHCQYGCAYHCgcICwgKCwkLCQcIDAgHCwgHCAYHCgcGDAgIDg0OEBETCQkKDAkHDAkHCQcGCQcHExAPGRYTFBEOCwgHDQkHDAkHCQcGBwcHCwwODw8QDAsKDQkHDQkH"], [0, "非武将头像", "zhujueaxian", "DQkHDQsJDg4NDw8PEhIREA4NDgkIEAkIDQkHDg4OEBEREBEREhISDw4NDQkIDQkHDQkHDg0MEA8PExAPGRMSEw4MDQkIDQkHDQkHDQkIDgoJFxAPGREPGBEPDgoIDQkHDQkHDQkHEw8NGBIQEg0LDgoIDQkHDQkH"], [0, "非武将头像", "zhujueaxian2", "DQkHCwgHCAcGBwcGBwYGCQcGDQkHDQkHDAkHCQcGBwYGBwYGCAcHCQcHDAkHDQkHDAkHCQcHCwkJDgsLFRAPEQ0MDQkHDQkHDQkHDg0MExMSGRMRGxIQGRIQDgoIDQkHDQkHDQsKDg4NFhEPFQ8NEQ0LDQkHDQkH"], [0, "非武将头像", "zhujueaxian3", "DQkHCwcGCAYFCAYGCQcGDAkHDQkHDQkHDAkHCQYGBwUFCQYGDQkJCwgHDQkHDQkHDQkHCwgHCQYGEQwLGhMRDwsKDAkHDQkHDQkHDAkHCgcHFxAPHRQSGRIQDgoIDQkHDQkHDQkHDwwKGBIQFQ8ODwsJDQkHDQkH"], [0, "非武将头像", "zhujueaxian5101", "DAkHDQYFDwgGFQ8GFA0FEQ0HDAkHDQkHDAkHDwoEEgwGEw4KFA8JEw4IDQkHDQkHDQkHDgkGFhAEFQ4JFhALEgwIDQgHDQkHDwYFDwYFEAoEFA4JGhMRFxAODQUFDgQEDgMCDQIBDgUCEgwHFQ4LEAkGDQQBDQMB"], [0, "非武将头像", "zhujueaxian5103", "CwQEFAwCDg4FCQkGDAgGDgsFDQkHDQkHCgQEDQgFDwsEDgsEDQoFDgkFDQkHDQkHCwYFCQUFCwcGEggGEQgFDQgGDQkHDQkHDwoEDQgECQYFEwwLGREPDQoIDAkHDQkHDgkECwkFCQcGCgcHDAkJCAcGCQgHDAkH"], [0, "非武将头像", "zhujueaxian5104", "DQkHDggGDwkGEg0LEBILDwkGDQgGDQkHDQkHDggFEAcEEAgFDQ4EDggEDQgGDQkHDQkHDQkHDgYEEgsJEgwJDwgGDQkHDQkHEAgEDggFEwkDFQwKHBUSFAwKDQgGDggFEggDEAcDEggDEAwKFA8NEgkGEAcDEAcD"], [0, "非武将头像", "zhujueaxian5105", "DQkHDAgHCwcGCQUFCgQFFAkJEAsIDQkHDQcGDwcGFQ4JGBEKEwkGFg4MEQsJDQkHDQUFEQUFFQ8MFQ8MFg0LGBIPFAwLDgcGDQkHDQoIDgsKDgoJEQcHFg0MGBEPDwkHDAkHCQYFBwUFDwwLFhAOEQsKDgoIDQkH"], [0, "非武将头像", "zhujueaxian5106", "EQkLFQcQEwkNEw4LEw4KEAkKDQkHDQkHEw8PEggIEQgFEwsEEwkEDwgGDQkHDQkHFBMSEw8OEAkGEAoIEQkGDgkHDQkHDQcIEgsMEg4NEQwLGBEPGhMQEgwKDQYGDwUIFAgGFAoGEwwHDwkIDwgIEAgGEAcEEAYI"], [0, "非武将头像", "zhujueaxian5107", "CwcGCAIDDAYDEQwKEggHEwsIEgsKDQkHCwcGCAIDCwYFEAwKEgsKEwoJEgoJDQkHDAgHCQQEDgkIFA8NFQ8NFA8MEAwKDQkHDQkHDQkGCwYFEAwKFRAOFxIQEQwKDQkHDwoGFQ4EEgwIEw4NFA8NEwwJEgsGDgkG"], [0, "非武将头像", "zhujueaxian5108", "DQoIEA4KDg0ICQ4IDg0FDgwGDw4JDQoIDQkHDgwJEQsGEAoFEQwGEAsGDQkGDQkHCQwICwoIEAwKFQ8NFg8MDwsJCgsICwwHChEIDA0HCw0JGBIPGRQRFBEOCg0ICRAHDw8FDw4FCw8IEg0IFA8KEA0JCw0HDA8F"], [0, "非武将头像", "zhujueaxian5109", "CwgHCgcGCQcIBAYOBgYLDQkGDQkHDQkHCwcGCgYEDQgDCQcHCgcHDwoFDQkHDQkHCgcGCgYECwYCDwkFDgkGDgkFDQkHDQkHCwsKCgoIDgoFFQ4KGhMQEA0KCAwNDAsJChAPBQwOCgsIEAoGEQwICQwMAw0PCwoI"], [0, "非武将头像", "zhujueaxian5111", "CQUFDQQDDAUFCgYGDQkHDQkHDQkHDQkHCAUGDQcFEQcFEQkFEQ0KDQkHDAgGDQkHCgYFDwoFEwsFEQoGFQ0FEwwFDQgFDQkHEAgEEAkFEAkFEQwLFQ4MEAkEDQYEDAgGEgoEEwoFEAkFDwkGDwkHDQYDDAQDDAYE"], [0, "非武将头像", "zhujueaxian5112", "DAkHCgUKDAgOFBITFhMSEQ0MDQkHDQkHDAgHCQYIEw8MFhMQEw8MEA0KDQkHDQkHDAkHCwcKEQwMFRAPFA8ODwsKDQkHDQkHDwsIEQ0MEAsOEQwQGBEPEgwQDQkJDQkHFBEOFxQQFxUSEw8QFRANDwoRDwwLDQkH"], [0, "非武将头像", "zhujueaxian5113", "DAkHBQwRBQ0TBAoRBA0YBQkQBwwQDAkICwgHBQUICQoLDgsICA0SDAoJCwoJDQkHCwoJCgcGCgYEDgcDDgcFDQcFDAkICAsODAsLCgoODAcEEQsGGBEOEAoHCwkLCQwQCAoRDQoMDggFDQoIEAsJDgoIDAkMCwkK"], [0, "非武将头像", "zhujueaxian5114", "CgcICw8ICxIKCQsJEQ0GDw0HDQkHDQkHCgcHDAoGCg8JBw0LDQ4IDg0HDAkHDQkHCwcHDQcFEQwFEA0JDw4MDQsJDQkHDQkHDAsHEQ4HEQwFEQ8KHBUSFxIPDQsIDQoHDhgLERoMEQ8HERAJFBALEhAIDhIJDQwI"], [0, "非武将头像", "zhujueaxian5116", "CgcGCgcGEQsHEg4KEAwKDwoGDQkHDQkHCgYGCQYFFA0GGBAIFxEMEAoGDQkHDQkHDQcMCwcIEwwGFw8LGBAMEAoHDQkHDQkHEw4TFREWEw0RFQwNGBAQEgwNDQkIDQkHGBQaGBQbGBQaEwsWEgkUDwYPDwgQDQkI"], [0, "非武将头像", "zhujueaxian5117", "EAQEEAUDEwkDFAYEEwYEEAYEDQkHDQkHDwUFEQcDEwoCEwgDFAkDEQgEDAgHDQgICgkMCggIEwwEFg0HFQoFDgkGBggLDwgIEQkHCwoJEgwFGBAKFw8HEgsEDwkGEggEEwkDFQwDEQoDEAkFEwsDEAkFEwoDDgYC"], [0, "非武将头像", "zhujueaxian5118", "DxQSBAoNCAwNEhQRCRENCwkIDQkHDQkHERYTBwsMBgsNDRIOBRQLCwoIDQkHDQkHCxAQCQkKCgkKDQsLDQ4MDAkIDQkHDQkHDA4ODQsLDQsLEw8OGBEQDQsLCgkIDQkHDxAODw4MDw4NCQkKDwwLDxIQBQoLCwkI"], [0, "非武将头像", "zhujueaxian5120", "DAYHEQoLFhENEw0NFA4OEQsKDQgIDQkHCwcJEQsMFhELFxMNFhMQDQYPDAgIDQkHDAgHCwUJDgcIEQsLEw4LDgkIDQkHDQkHEA0JEgwHEQoJEgoSGhMREw0IEQwHDgkHFQ8IFA8GEQ0EEgwJFA4JEQ4FFA8HDgoH"], [0, "非武将头像", "zhujueaxian5121", "DgkHGAsDFg0DGxMGGhEHEgwIDQkHDQkHDQkHFAoEGg0CFxAHGRIIGREIDgoHDQkHDQkHEAkFGA0EFQ4KEwwJFQoEDgkGDQkHDQkHDggFEQoFFg8MGhMQEQkGDgkGDQkHFAkDFAsEEQgFEgkFFQsHDgUEEQkEDgoG"], [0, "非武将头像", "zhujueaxian6001", "DQkHEAwLEgwMFA8PEA8PDQoKDgoIDQkHDQkHEQwLEgsKEA0NEQ8PDQsLDQoJDQkHDQkHDwoJEQkJCwgJBwUGBAICCAUEDQkHDQkHDAkHCwkJFQ0NFRAQFA8PEAwLDQkHDQkHDAgGDQoJFQ0NFBEQExEQDgsKDQkH"], [0, "非武将头像", "zhujueaxian_sdsl9", "GhQfFxEZDgkMFA0VFQ8WDgoMDwsLDQkHFQ8ZEAoSDAcLDw0PEQ8SDg0ODwsMDQkHDAkICgYKEAoQExATFBMVEBAREAsNDQkHDAoJDQwOExAUEw4VFBQVDw4PDQoLDAkHDw8QDg4PDg0ODwoPEQ0PDAoNDAkLDAoK"], [313, "祝融夫人", "zhurongfuren", "DQgHDgYFEgwKFhIPFBIPEA0LDQoIDQkHDQgGEwkFGBURFhIQEwsJFA0MDgoJDQkHDQkHEg0LFxQRFQ8NFgwJEwwJDgoJDQkHDQkHDwsJFBAOFg0JGQ8JEwwJDwsJDQkHDQkHDQkIEg4MFQ4LFQwIEgwKDQkHDQkH"]];
  var v4 = null;
  var vO12 = {
    patched: [],
    items: [],
    teamCache: new Map(),
    formationCache: new Map(),
    pending: new Map(),
    imagePending: new Map(),
    activeRequests: new Set(),
    requestChain: Promise.resolve(),
    formationCacheHits: 0,
    formationRecognitionRuns: 0,
    requestObservers: [],
    internalTeamRequestDepth: 0,
    lastExternalTeamRequestAt: 0,
    activeTeamRequestConflict: null,
    retryTimer: 0,
    destroyed: false
  };
  function f() {
    var v5 = Array.prototype.slice.call(arguments);
    v5.unshift("[SaltQueueLocker]");
    console.log.apply(console, v5);
  }
  function f2() {
    var v6 = Array.prototype.slice.call(arguments);
    v6.unshift("[SaltQueueLocker]");
    console.warn.apply(console, v6);
  }
  function f3() {
    var v_0x22dee1 = f20();
    var v7;
    var v8;
    if (!v_0x22dee1 || typeof v_0x22dee1.sendGetTeamInfo !== "function") {
      return false;
    }
    if (vO12.requestObservers.some(function (p3) {
      return p3.war === v_0x22dee1;
    })) {
      return true;
    }
    v7 = v_0x22dee1.sendGetTeamInfo;
    v8 = function () {
      if (vO12.internalTeamRequestDepth <= 0) {
        vO12.lastExternalTeamRequestAt = Date.now();
        if (typeof vO12.activeTeamRequestConflict === "function") {
          vO12.activeTeamRequestConflict();
        }
      }
      return v7.apply(this, arguments);
    };
    v_0x22dee1.sendGetTeamInfo = v8;
    var vO13 = {
      war: v_0x22dee1,
      original: v7,
      wrapped: v8
    };
    vO12.requestObservers.push(vO13);
    return true;
  }
  function f4() {
    vO12.requestObservers.forEach(function (p4) {
      if (p4.war && p4.war.sendGetTeamInfo === p4.wrapped) {
        p4.war.sendGetTeamInfo = p4.original;
      }
    });
    vO12.requestObservers = [];
    vO12.activeTeamRequestConflict = null;
  }
  function f5() {
    var v9 = Date.now();
    return new Promise(function (p5) {
      function f6() {
        var v10 = Date.now();
        var v11 = v10 - Number(vO12.lastExternalTeamRequestAt || 0);
        if (vO12.destroyed) {
          p5(false);
          return;
        }
        if (v11 >= vLN250 || v10 - v9 >= vLN750) {
          p5(true);
          return;
        }
        window.setTimeout(f6, Math.min(vLN250 - v11, 50));
      }
      f6();
    });
  }
  function f7() {
    vO12.teamCache.clear();
    vO12.formationCache.clear();
    vO12.imagePending.clear();
    try {
      window.localStorage.removeItem(vLSBabayuSaltFieldForma);
    } catch (e) {}
  }
  function f8(p6) {
    var v12;
    var v13;
    var v14;
    var v15;
    var v16;
    if (!p6 || typeof p6 !== "object") {
      return null;
    }
    v12 = String(p6.label || "").slice(0, 20);
    v14 = Math.max(0, Math.min(5, Number(p6.total) || 0));
    v13 = Math.max(0, Math.min(v14, Number(p6.alive) || 0));
    if (!v12 || v12 === "未知" || v12 === "空阵" || !v14) {
      return null;
    }
    v15 = Array.isArray(p6.heroIds) ? p6.heroIds.slice(0, 5).map(function (p7) {
      return Math.max(0, Number(p7) || 0);
    }) : [];
    v16 = Array.isArray(p6.heroNames) ? p6.heroNames.slice(0, 5).map(function (p8) {
      return String(p8 || "").slice(0, 20);
    }) : [];
    return {
      label: v12,
      alive: v13,
      total: v14,
      heroIds: v15,
      heroNames: v16,
      rosterFingerprint: "",
      remainingText: v13 + "/" + v14,
      text: v12 + v13 + "/" + v14,
      cachedAt: Number(p6.cachedAt) || Date.now(),
      persisted: true
    };
  }
  function f9() {
    var vO14 = {};
    try {
      vO12.teamCache.forEach(function (p9, p10) {
        var vF8 = f8(p9);
        if (vF8) {
          vO14[String(p10)] = vF8;
        }
      });
      var vO15 = {
        version: 1,
        entries: vO14
      };
      window.localStorage.setItem(vLSBabayuSaltFieldForma, JSON.stringify(vO15));
    } catch (e2) {
      f2("阵容缓存写入失败:", e2 && e2.message || e2);
    }
  }
  function f10() {
    var v17;
    var v18;
    var v19 = Date.now();
    try {
      v17 = JSON.parse(window.localStorage.getItem(vLSBabayuSaltFieldForma) || "{}");
      v18 = v17 && v17.version === 1 && v17.entries || {};
      Object.keys(v18).slice(-vLN1200).forEach(function (p11) {
        var vF82 = f8(v18[p11]);
        if (!vF82 || v19 - vF82.cachedAt > vLN15552000000) {
          return;
        }
        vO12.teamCache.set(p11, vF82);
        vO12.formationCache.set(p11, {
          label: vF82.label,
          heroIds: vF82.heroIds.slice(),
          heroNames: vF82.heroNames.slice(),
          rosterFingerprint: "",
          identifiedAt: vF82.cachedAt
        });
      });
    } catch (e3) {
      f2("阵容缓存读取失败:", e3 && e3.message || e3);
    }
  }
  function f11(p12) {
    var v20 = window.atob || (typeof atob === "function" ? atob : null);
    var v21;
    var v22;
    var v23;
    if (!v20 || !p12) {
      return null;
    }
    v21 = v20(p12);
    v22 = new Uint8Array(v21.length);
    for (v23 = 0; v23 < v21.length; v23++) {
      v22[v23] = v21.charCodeAt(v23);
    }
    return v22;
  }
  function f12() {
    if (v4) {
      return v4;
    }
    v4 = vA2.map(function (p13) {
      return {
        heroId: Number(p13[0]),
        heroName: String(p13[1]),
        variant: String(p13[2]),
        signature: f11(p13[3])
      };
    }).filter(function (p14) {
      return p14.heroId >= 0 && p14.signature && p14.signature.length > 0;
    });
    return v4;
  }
  function f13(p15, p16) {
    var vLN0 = 0;
    var v24;
    if (!p15 || !p16 || p15.length !== p16.length || !p15.length) {
      return Infinity;
    }
    for (v24 = 0; v24 < p15.length; v24++) {
      vLN0 += Math.abs(p15[v24] - p16[v24]);
    }
    return vLN0 / p15.length;
  }
  function f14(p17) {
    var vO16 = {};
    var v25;
    f12().forEach(function (p18) {
      var vF13 = f13(p17, p18.signature);
      var v26 = p18.heroId + ":" + p18.heroName;
      var v27 = vO16[v26];
      if (!v27 || vF13 < v27.distance) {
        var vO17 = {
          heroId: p18.heroId,
          heroName: p18.heroName,
          variant: p18.variant,
          distance: vF13
        };
        vO16[v26] = vO17;
      }
    });
    v25 = Object.keys(vO16).map(function (p19) {
      return vO16[p19];
    }).sort(function (p20, p21) {
      return p20.distance - p21.distance;
    });
    if (!v25.length) {
      return null;
    }
    v25[0].margin = v25.length > 1 ? v25[1].distance - v25[0].distance : Infinity;
    v25[0].accepted = v25[0].heroId > 0 && v25[0].distance <= vLN15 && v25[0].margin >= vLN05;
    v25[0].second = v25[1] || null;
    return v25[0];
  }
  function f15(p22) {
    return new Promise(function (p23, p24) {
      var v28 = window.Image || (typeof Image !== "undefined" ? Image : null);
      var v29;
      if (!v28 || typeof document === "undefined" || typeof document.createElement !== "function") {
        p24(new Error("当前环境不支持 Canvas 图片识别"));
        return;
      }
      v29 = new v28();
      v29.onload = function () {
        try {
          var v30 = document.createElement("canvas");
          var v31;
          var v32;
          var v33 = new Uint8Array(vLN8 * vLN5 * 3);
          var v34;
          var vLN02 = 0;
          v30.width = vLN8;
          v30.height = vLN5;
          v31 = v30.getContext("2d", {
            willReadFrequently: true
          });
          v31.fillStyle = "rgb(105,77,61)";
          v31.fillRect(0, 0, v30.width, v30.height);
          v31.drawImage(v29, 0, 0, v30.width, v30.height);
          v32 = v31.getImageData(0, 0, v30.width, v30.height).data;
          for (v34 = 0; v34 < v32.length; v34 += 4) {
            v33[vLN02++] = v32[v34] >> 3;
            v33[vLN02++] = v32[v34 + 1] >> 3;
            v33[vLN02++] = v32[v34 + 2] >> 3;
          }
          p23(v33);
        } catch (e4) {
          p24(e4);
        }
      };
      v29.onerror = function () {
        p24(new Error("头像 PNG 解码失败"));
      };
      v29.src = String(p22 || "");
    });
  }
  function f16(p25) {
    return f15(p25).then(function (p26) {
      return f14(p26);
    });
  }
  function f17() {
    return typeof window.__require === "function";
  }
  function f18(p27) {
    return window.__require(p27);
  }
  function f19() {
    if (typeof fgui !== "undefined") {
      return fgui;
    }
    return window.fgui || null;
  }
  function f20() {
    if (!f17()) {
      return null;
    }
    try {
      var vF18 = f18("Configs");
      var vF182 = f18("ModuleManager");
      if (!vF18 || !vF182 || typeof vF182.GET_MODULE !== "function") {
        return null;
      }
      return vF182.GET_MODULE(vF18.ModuleType.LEGION_WAR);
    } catch (e5) {
      return null;
    }
  }
  function f21(p28) {
    var v35;
    var v36;
    for (v35 = 0; v35 < p28.length; v35++) {
      v36 = Number(p28[v35]);
      if (isFinite(v36) && v36 > 0) {
        return v36;
      }
    }
    return 0;
  }
  function f22(p29) {
    if (!p29) {
      return null;
    }
    try {
      return p29._serverData || p29.serverData || null;
    } catch (e6) {
      return null;
    }
  }
  function f23(p30) {
    var v37;
    if (!p30) {
      return 0;
    }
    v37 = f22(p30);
    return f21([p30.id, p30.roleId, p30.roleCodeId, v37 && v37.codeIdV2, p30.key, p30.team && p30.team.leaderId, p30.team && p30.team.leaderRoleId, p30.codeIdV2, p30.codeId, p30.cId, p30.team && p30.team.leaderCodeIdV2, p30.team && p30.team.leaderCodeId, p30.hasTeam && p30.team && p30.team.leaderId]);
  }
  function f24() {
    var vF20 = f20();
    if (!vF20) {
      return null;
    }
    return vF20.battlefield || vF20._battlefield || vF20.data && vF20.data.battlefield || null;
  }
  function f25() {
    var vF202 = f20();
    var vF24 = f24();
    if (!vF202) {
      return "unknown";
    }
    return String(vF202.battlefieldId || vF202._battlefieldId || vF24 && vF24.id || vF202.data && vF202.data.battlefieldId || "unknown");
  }
  function f26(p31) {
    return p31 && (p31.name || p31.nickName || p31.roleName || p31.nickname) || "";
  }
  function f27(p32) {
    var vF23 = f23(p32);
    var vF203 = f20();
    var vF242 = f24();
    var v38 = vF242 && (vF242.self || vF242.selfRole || vF242.role);
    var vF21 = f21([v38 && v38.id, v38 && v38.roleId, v38 && v38.roleCodeId, vF203 && vF203.selfCodeId, vF203 && vF203._selfCodeId, vF203 && vF203.roleId]);
    if (!vF23 || !vF203) {
      return false;
    }
    return vF23 === vF21;
  }
  function f28(p33) {
    return !!p33 && typeof p33 === "object" && (!!p33.id || !!p33.roleId || !!p33.roleCodeId || !!p33.key || !!p33.codeId || !!p33.codeIdV2 || !!p33.cId || !!p33.name || !!p33.nickName || !!p33.roleName);
  }
  function f29(p34) {
    var vF232 = f23(p34);
    if (vF232) {
      return f25() + ":" + vF232;
    } else {
      return "";
    }
  }
  function f30(p35, p36) {
    if (!p35) {
      return null;
    }
    if (typeof p35.get === "function") {
      if (!p35.has || p35.has(p36)) {
        return p35.get(p36);
      }
      if (p35.has(String(p36))) {
        return p35.get(String(p36));
      }
      return null;
    }
    if (Object.prototype.hasOwnProperty.call(p35, p36)) {
      return p35[p36];
    }
    if (Object.prototype.hasOwnProperty.call(p35, String(p36))) {
      return p35[String(p36)];
    }
    return null;
  }
  function f31(p37, p38) {
    if (!p37 || typeof p38 !== "function") {
      return;
    }
    if (typeof p37.forEach === "function") {
      p37.forEach(function (p39, p40) {
        p38(p39, p40);
      });
      return;
    }
    if (typeof p37 === "object") {
      Object.keys(p37).forEach(function (p41) {
        p38(p37[p41], p41);
      });
    }
  }
  function f32(p42) {
    var vO19 = {};
    if (!p42 || typeof p42 !== "object") {
      return vO19;
    }
    Object.keys(p42).forEach(function (p43) {
      vO19[p43] = p42[p43];
    });
    return vO19;
  }
  function f33(p44) {
    if (p44 === null || p44 === undefined || p44 === "") {
      return -1;
    }
    var vNumber = Number(p44);
    if (isFinite(vNumber) && vNumber >= 0 && vNumber < 5 && Math.floor(vNumber) === vNumber) {
      return vNumber;
    } else {
      return -1;
    }
  }
  function f34(p45, p46, p47) {
    var vA3 = [p45 && p45.battleTeamSlot, p45 && p45.slot, p45 && p45.index, p46, p47];
    var v39;
    var v40;
    for (v39 = 0; v39 < vA3.length; v39 += 1) {
      v40 = f33(vA3[v39]);
      if (v40 >= 0) {
        return v40;
      }
    }
    return -1;
  }
  function f35() {
    var vF243 = f24();
    var v41 = vF243 && (vF243.players || vF243.roles);
    var vA4 = [];
    var vO20 = {};
    function f36(p48, p49) {
      var v42 = f23(p48) || f21([p49]);
      var v43;
      if (!v42 || vO20[v42]) {
        return;
      }
      vO20[v42] = true;
      v43 = vO12.teamCache.get(f25() + ":" + v42) || null;
      vA4.push({
        roleCodeId: v42,
        name: f26(p48),
        strength: p48 && p48.strength,
        state: p48 && p48.state,
        formation: v43 && v43.text || ""
      });
    }
    if (v41 && typeof v41.forEach === "function") {
      v41.forEach(function (p50, p51) {
        f36(p50, p51);
      });
    } else if (v41 && typeof v41 === "object") {
      Object.keys(v41).forEach(function (p52) {
        f36(v41[p52], p52);
      });
    }
    return vA4.sort(function (p53, p54) {
      return p53.roleCodeId - p54.roleCodeId;
    });
  }
  function f37(p55) {
    if (!p55) {
      return "";
    }
    return String(p55).replace(/^data:image\/png;base64,/, "");
  }
  function f38(p56) {
    var vA5 = [null, null, null, null, null];
    var vA6 = [];
    var vLN03 = 0;
    if (!p56) {
      return [];
    }
    f31(p56, function (p57, p58) {
      var v44;
      var v45;
      if (!p57 || typeof p57 !== "object" || vLN03 >= 5) {
        return;
      }
      v44 = f32(p57);
      v45 = f34(v44, p58, -1);
      v44.__saltTeamKey = p58;
      v44.__saltTeamSlot = v45;
      if (v45 >= 0 && !vA5[v45]) {
        vA5[v45] = v44;
      } else {
        vA6.push(v44);
      }
      vLN03 += 1;
    });
    vA6.forEach(function (p59) {
      var v46;
      for (v46 = 0; v46 < 5; v46 += 1) {
        if (!vA5[v46]) {
          p59.__saltTeamSlot = v46;
          vA5[v46] = p59;
          break;
        }
      }
    });
    return vA5.filter(function (p60) {
      return !!p60;
    });
  }
  function f39(p61, p62) {
    var vA7 = [];
    var vO21 = {};
    (p61 || []).slice(0, 5).forEach(function (p63, p64) {
      var vF32 = f32(p63);
      var v47 = p63 && p63.__saltTeamKey;
      var vF34 = f34(vF32, v47, p64);
      var vF37 = f37(f30(p62, v47) || f30(p62, vF34));
      if (vF34 >= 0 && vO21[vF34]) {
        return;
      }
      if (vF34 >= 0) {
        vO21[vF34] = true;
      }
      vF32.__saltTeamKey = v47;
      vF32.__saltTeamSlot = vF34;
      if (vF37) {
        vF32.imgName = vF37;
      }
      if (vF37 && !vF32.heroName) {
        vF32.heroName = "未知头像";
      }
      if (vF32.curHp === undefined && vF32.hp === undefined) {
        vF32.curHp = 1;
      }
      vA7.push(vF32);
    });
    return vA7;
  }
  function f40(p65) {
    var v48 = null;
    if (!p65) {
      return null;
    }
    if (Array.isArray(p65.formation)) {
      v48 = p65.formation;
    } else if (Array.isArray(p65.fighters)) {
      v48 = p65.fighters;
    } else if (Array.isArray(p65.heroes)) {
      v48 = p65.heroes;
    } else if (p65.teamInfo) {
      v48 = f39(f38(p65.teamInfo), p65.teamImgInfo);
    } else if (p65.battleTeam) {
      v48 = f38(p65.battleTeam);
    }
    if (!v48 || !v48.length) {
      return null;
    }
    return v48.slice(0, 5).map(function (p66, p67) {
      var vF372 = f37(p66 && (p66.imgName || p66.teamImg || p66.imgHash || p66.imageHash));
      var v49 = Number(p66 && (p66.heroId || p66.confId || p66.heroConfId || p66.id)) || 0;
      return {
        heroId: v49,
        heroName: p66 && (p66.heroName || p66.name) || vVO2[v49] || (vF372 ? "未知头像" : ""),
        imgName: vF372,
        battleTeamSlot: f34(p66, null, p67),
        curHp: p66 && p66.curHp !== undefined ? p66.curHp : p66 && p66.hp !== undefined ? p66.hp : 1,
        useSkin: p66 && p66.useSkin
      };
    }).filter(function (p68) {
      return p68.heroId > 0 || !!p68.imgName || !!p68.heroName;
    });
  }
  function f41(p69, p70) {
    if (!p69) {
      return "";
    }
    if (p69.heroName) {
      return String(p69.heroName);
    }
    if (!p69.heroId) {
      return "";
    }
    if (vVO2[p69.heroId]) {
      return vVO2[p69.heroId];
    }
    try {
      var v50 = f18("HeroDataView").HeroDataView;
      if (v50 && v50.getRealName) {
        var v51 = v50.getRealName(p69, p69.useSkin, !!p70 && !!f27(p70));
        if (v51) {
          return String(v51);
        }
      }
    } catch (e7) {}
    try {
      var vF183 = f18("Configs");
      var vF184 = f18("LanguageExt");
      var v52 = vF183.HeroConf && vF183.HeroConf.getById(p69.heroId);
      var v53 = v52 && (v52.nickName || v52.name);
      if (v53 && vF184 && vF184.GET_CONTENT) {
        return String(vF184.GET_CONTENT(v53));
      }
      if (v53) {
        return String(v53);
      } else {
        return String(p69.heroId);
      }
    } catch (e8) {
      return String(p69.heroId);
    }
  }
  function f42(p71, p72) {
    return p71.some(function (p73) {
      return String(p73 || "").indexOf(p72) >= 0;
    });
  }
  function f43(p74, p75, p76, p77) {
    var v54;
    if (p76 > 0 && p75 <= 0) {
      return "空阵";
    }
    if (p76 > 0 && p75 <= 3) {
      return "残阵";
    }
    for (v54 = 0; v54 < vA.length; v54++) {
      var v55 = vA[v54];
      var v56 = v55.heroes.every(function (p78) {
        return f42(p74, p78);
      });
      if (v56) {
        return v55.label;
      }
    }
    if (p76 > 0 && p77 && ["未知", "空阵", "残阵"].indexOf(p77) < 0) {
      return p77;
    }
    if (p76 > 0) {
      return "其他";
    }
    return "未知";
  }
  function f44(p79) {
    var vO22 = {};
    (p79 || []).forEach(function (p80, p81) {
      var v57;
      if (!p80) {
        return;
      }
      v57 = f34(p80, p80.__saltTeamKey, p81);
      if (v57 < 0 || vO22[v57]) {
        return;
      }
      vO22[v57] = [v57, Number(p80.heroId) || 0, Number(p80.level) || 0, Number(p80.order) || 0, Number(p80.star) || 0, Number(p80.color) || 0, Number(p80.power) || 0, Number(p80.maxHp || p80.hp) || 0, Number(p80.useSkin) || 0, f37(p80.imgName).toLowerCase()].join(":");
    });
    if (Object.keys(vO22).length !== 5) {
      return "";
    }
    return [0, 1, 2, 3, 4].map(function (p82) {
      return vO22[p82];
    }).join("|");
  }
  function f45(p83, p84, p85) {
    var vA8 = [];
    var vA9 = [];
    var vLN04 = 0;
    var vO23 = {};
    p84 = p84 || [];
    p84.forEach(function (p86, p87) {
      var v58;
      var v59;
      if (!p86) {
        return;
      }
      v59 = f34(p86, p86.__saltTeamKey, p87);
      if (v59 >= 0 && vO23[v59]) {
        return;
      }
      if (v59 >= 0) {
        vO23[v59] = true;
      }
      v58 = f41(p86, p83);
      if (p86.heroId) {
        vA9.push(p86.heroId);
      }
      if (v58) {
        vA8.push(v58);
      }
      var v60 = p86.curHp;
      var v61 = p86.hp;
      var v62 = false;
      if (v60 !== undefined && v60 !== null && v60 !== "") {
        v62 = isFinite(Number(v60)) && Number(v60) === 0;
      } else if (v61 !== undefined && v61 !== null && v61 !== "") {
        v62 = isFinite(Number(v61)) && Number(v61) === 0;
      }
      if (!v62) {
        vLN04++;
      }
    });
    var v63 = p84.length ? 5 : 0;
    var vF43 = f43(vA8, vLN04, v63, p85 && p85.label || p83 && p83.formationType);
    if (!vA8.length && p85 && p85.heroNames) {
      vA8 = p85.heroNames.slice();
    }
    if (!vA9.length && p85 && p85.heroIds) {
      vA9 = p85.heroIds.slice();
    }
    return {
      label: vF43,
      alive: vLN04,
      total: v63,
      heroIds: vA9,
      heroNames: vA8,
      rosterFingerprint: f44(p84),
      remainingText: vLN04 + "/" + v63,
      text: vF43 + vLN04 + "/" + v63
    };
  }
  function f46(p88) {
    if (!p88) {
      return null;
    }
    if (p88.code) {
      return null;
    }
    if (p88.data && p88.data.code) {
      return null;
    }
    if (typeof p88.getData === "function") {
      try {
        var vF185 = f18("data-index");
        return p88.getData(new vF185.War_GetTeamInfoResp());
      } catch (e9) {
        try {
          return p88.getData();
        } catch (e10) {
          return null;
        }
      }
    }
    if (p88.data && typeof p88.data.getData === "function") {
      try {
        var vF186 = f18("data-index");
        return p88.data.getData(new vF186.War_GetTeamInfoResp());
      } catch (e11) {
        try {
          return p88.data.getData();
        } catch (e12) {
          return null;
        }
      }
    }
    if (p88.body && (p88.body.teamInfo || p88.body.teamImgInfo)) {
      return p88.body;
    }
    return p88.data || p88;
  }
  function f47(p89) {
    var vF46 = f46(p89);
    if (!vF46 || !vF46.teamInfo) {
      return null;
    }
    return f39(f38(vF46.teamInfo), vF46.teamImgInfo);
  }
  function f48(p90) {
    if (!p90) {
      return null;
    }
    if (p90.code || p90.data && p90.data.code) {
      return null;
    }
    if (typeof p90.getData === "function") {
      try {
        var vF187 = f18("data-index");
        return p90.getData(new vF187.War_GetTeamImgInfoResp());
      } catch (e13) {
        try {
          return p90.getData();
        } catch (e14) {
          return null;
        }
      }
    }
    if (p90.data && typeof p90.data.getData === "function") {
      try {
        var vF188 = f18("data-index");
        return p90.data.getData(new vF188.War_GetTeamImgInfoResp());
      } catch (e15) {
        try {
          return p90.data.getData();
        } catch (e16) {
          return null;
        }
      }
    }
    if (p90.body && p90.body.teamInfo) {
      return p90.body;
    }
    return p90.data || p90;
  }
  function f49(p91) {
    var vF48 = f48(p91);
    return vF48 && vF48.teamInfo || null;
  }
  function f50(p92, p93) {
    return !!p92 && !!p93.some(function (p94) {
      return !!f30(p92, p94);
    });
  }
  function f51(p95) {
    var vF204 = f20();
    if (!p95 || !p95.length || !vF204 || typeof vF204.sendGetTeamImgInfo !== "function") {
      return Promise.resolve(null);
    }
    return new Promise(function (p96) {
      var v64 = false;
      var vLN06 = 0;
      var v65 = null;
      var v66 = false;
      function f52() {
        if (v66 && v65 && vF204.network && typeof vF204.network.off === "function") {
          vF204.network.off(v65, f56, vO12);
        }
        v66 = false;
      }
      function f53() {
        if (vLN06) {
          window.clearTimeout(vLN06);
        }
        vLN06 = 0;
        f52();
        vO12.activeRequests.delete(f55);
      }
      function f54(p97) {
        if (v64) {
          return;
        }
        v64 = true;
        f53();
        p96(p97 || null);
      }
      function f55() {
        f54(null);
      }
      function f56(p98) {
        var vF49 = f49(p98);
        if (f50(vF49, p95)) {
          f54(vF49);
        }
      }
      try {
        var vF189 = f18("data-index");
        v65 = vF189.RESPS && vF189.RESPS.War_GetTeamImgInfoResp;
        if (v65 && vF204.network && typeof vF204.network.on === "function") {
          vF204.network.on(v65, f56, vO12);
          v66 = true;
        }
      } catch (e17) {}
      vO12.activeRequests.add(f55);
      vLN06 = window.setTimeout(function () {
        f54(null);
      }, 3500);
      try {
        var v67 = vF204.sendGetTeamImgInfo(p95.slice());
        if (v67 && typeof v67.then === "function") {
          v67.then(function (p99) {
            var vF492 = f49(p99);
            if (f50(vF492, p95)) {
              f54(vF492);
            }
          }).catch(function (p100) {
            f2("头像图片读取失败:", p100 && p100.message || p100);
          });
        } else if (v67) {
          var vF493 = f49(v67);
          if (f50(vF493, p95)) {
            f54(vF493);
          }
        }
      } catch (e18) {
        f2("头像图片请求异常:", e18 && e18.message || e18);
        f54(null);
        return;
      }
    });
  }
  function f57(p101, p102) {
    return (p101 || []).map(function (p103) {
      var vF322 = f32(p103);
      var v68 = f37(vF322 && vF322.imgName).toLowerCase();
      var v69 = v68 && p102 && p102[v68];
      if (v69) {
        vF322.heroId = v69.heroId;
        vF322.heroName = v69.heroName || v69.name;
      }
      return vF322;
    });
  }
  function f58(p104, p105) {
    var v70 = vO12.imagePending.get(p104);
    if (v70) {
      return v70;
    }
    v70 = f16(p105).then(function (p106) {
      if (vO12.destroyed) {
        return null;
      }
      if (p106 && p106.accepted) {
        var vO24 = {
          heroId: p106.heroId,
          heroName: p106.heroName,
          variant: p106.variant,
          distance: p106.distance,
          margin: p106.margin,
          accepted: true
        };
        return vO24;
      }
      if (p106) {
        f("头像未达到自动确认阈值:", p104, p106.heroName, "distance=" + p106.distance.toFixed(3), "margin=" + p106.margin.toFixed(3));
      }
      return null;
    }).catch(function (p107) {
      f2("头像识别失败:", p104, p107 && p107.message || p107);
      return null;
    }).then(function (p108) {
      vO12.imagePending.delete(p104);
      return p108;
    });
    vO12.imagePending.set(p104, v70);
    return v70;
  }
  function f59(p109) {
    var vA10 = [];
    var vO25 = {};
    (p109 || []).forEach(function (p110) {
      var v71 = f37(p110 && p110.imgName).toLowerCase();
      if (!v71 || vO25[v71]) {
        return;
      }
      vO25[v71] = true;
      vA10.push(v71);
    });
    if (!vA10.length) {
      return Promise.resolve(f57(p109, {}));
    }
    return f51(vA10).then(function (p111) {
      if (!p111) {
        return f57(p109, {});
      }
      return Promise.all(vA10.map(function (p112) {
        var vF30 = f30(p111, p112);
        if (vF30) {
          return f58(p112, vF30);
        } else {
          return Promise.resolve(null);
        }
      })).then(function (p113) {
        var vO26 = {};
        vA10.forEach(function (p114, p115) {
          if (p113[p115]) {
            vO26[p114] = p113[p115];
          }
        });
        return f57(p109, vO26);
      });
    });
  }
  function f60(p116) {
    var vF29 = f29(p116);
    var v72 = vF29 ? vO12.teamCache.get(vF29) || null : null;
    var v73;
    if (!v72) {
      return null;
    }
    v73 = v72.persisted ? vLN15552000000 : vLN21600000;
    if (Date.now() - Number(v72.cachedAt || 0) > v73) {
      vO12.teamCache.delete(vF29);
      vO12.formationCache.delete(vF29);
      f9();
      return null;
    }
    return v72;
  }
  function f61(p117, p118) {
    var vF292 = f29(p117);
    if (!vO12.destroyed && vF292 && p118) {
      p118.cachedAt = Date.now();
      p118.persisted = true;
      vO12.teamCache.delete(vF292);
      vO12.teamCache.set(vF292, p118);
      while (vO12.teamCache.size > vLN1200) {
        vO12.teamCache.delete(vO12.teamCache.keys().next().value);
      }
      f9();
    }
  }
  function f62(p119) {
    var vF293 = f29(p119);
    if (vF293) {
      return vO12.formationCache.get(vF293) || null;
    } else {
      return null;
    }
  }
  function f63(p120, p121) {
    var vF294 = f29(p120);
    if (vO12.destroyed || !vF294 || !p121 || !p121.label || p121.label === "未知" || p121.label === "空阵") {
      return;
    }
    vO12.formationCache.delete(vF294);
    vO12.formationCache.set(vF294, {
      label: p121.label,
      heroIds: (p121.heroIds || []).slice(),
      heroNames: (p121.heroNames || []).slice(),
      rosterFingerprint: p121.rosterFingerprint || "",
      identifiedAt: Date.now()
    });
    while (vO12.formationCache.size > vLN1200) {
      vO12.formationCache.delete(vO12.formationCache.keys().next().value);
    }
  }
  function f64(p122, p123) {
    var vF62 = f62(p122);
    var vF44 = f44(p123);
    var v74 = !!vF62 && (!vF44 || !!vF62.rosterFingerprint && vF62.rosterFingerprint === vF44);
    if (v74) {
      vO12.formationCacheHits += 1;
      return Promise.resolve(f45(p122, p123, vF62));
    }
    if (!p123.length) {
      return Promise.resolve(f45(p122, p123, vF62));
    }
    vO12.formationRecognitionRuns += 1;
    return f59(p123).then(function (p124) {
      var vF45 = f45(p122, p124 || p123);
      vF45.rosterFingerprint = vF44;
      f63(p122, vF45);
      return vF45;
    }).catch(function (p125) {
      f2("未知头像识别流程失败:", p125 && p125.message || p125);
      var vF452 = f45(p122, p123, vF62);
      vF452.rosterFingerprint = vF44;
      if (!vF62) {
        f63(p122, vF452);
      }
      return vF452;
    });
  }
  function f65(p126, p127, p128) {
    var vF205 = f20();
    if (!vF205 || typeof vF205.sendGetTeamInfo !== "function") {
      return Promise.resolve(null);
    }
    p128 = Number(p128) || 0;
    f3();
    return f5().then(function (p129) {
      if (!p129 || vO12.destroyed) {
        return null;
      }
      return new Promise(function (p130) {
        var v75 = false;
        var vLN07 = 0;
        var v76 = null;
        var v77 = false;
        function f66() {
          if (v77 && v76 && vF205.network && typeof vF205.network.off === "function") {
            vF205.network.off(v76, f71, vO12);
          }
          v77 = false;
        }
        function f67() {
          if (vLN07) {
            window.clearTimeout(vLN07);
          }
          vLN07 = 0;
          f66();
          if (vO12.activeTeamRequestConflict === f70) {
            vO12.activeTeamRequestConflict = null;
          }
          vO12.activeRequests.delete(f69);
        }
        function f68(p131) {
          if (v75) {
            return;
          }
          v75 = true;
          f67();
          if (p131 === vO) {
            p130(vO);
            return;
          }
          if (!Array.isArray(p131)) {
            p130(null);
            return;
          }
          f64(p126, p131).then(p130);
        }
        function f69() {
          f68(null);
        }
        function f70() {
          f68(vO);
        }
        function f71(p132) {
          var vF47 = f47(p132);
          f68(Array.isArray(vF47) ? vF47 : null);
        }
        try {
          var vF1810 = f18("data-index");
          v76 = vF1810.RESPS && vF1810.RESPS.War_GetTeamInfoResp;
          if (v76 && vF205.network && typeof vF205.network.on === "function") {
            vF205.network.on(v76, f71, vO12);
            v77 = true;
          }
        } catch (e19) {}
        vO12.activeRequests.add(f69);
        vO12.activeTeamRequestConflict = f70;
        vLN07 = window.setTimeout(function () {
          f68(null);
        }, 3500);
        try {
          var v78;
          vO12.internalTeamRequestDepth += 1;
          try {
            v78 = vF205.sendGetTeamInfo(p127);
          } finally {
            vO12.internalTeamRequestDepth -= 1;
          }
          if (v78 && typeof v78.then === "function") {
            v78.then(function (p133) {
              var vF472 = f47(p133);
              if (Array.isArray(vF472)) {
                f68(vF472);
              }
            }).catch(function (p134) {
              f2("阵容读取失败:", f26(p126) || p127, p134 && p134.message || p134);
            });
          } else if (v78) {
            var vF473 = f47(v78);
            if (Array.isArray(vF473)) {
              f68(vF473);
            }
          }
        } catch (e20) {
          f2("阵容请求异常:", f26(p126) || p127, e20 && e20.message || e20);
          f68(null);
          return;
        }
      });
    }).then(function (p135) {
      if (p135 === vO) {
        if (p128 < vLN2) {
          return f65(p126, p127, p128 + 1);
        }
        return null;
      }
      return p135;
    });
  }
  function f72(p136, p137) {
    var vF295 = f29(p136);
    var vF233 = f23(p136);
    var vF60 = f60(p136);
    var vF40 = f40(p136);
    var v79;
    if (vF60) {
      if (p137) {
        p137(vF60);
      }
      return Promise.resolve(vF60);
    }
    if (!vF295 || !vF233) {
      return Promise.resolve(null);
    }
    if (vO12.pending.has(vF295)) {
      return vO12.pending.get(vF295).then(function (p138) {
        if (!vO12.destroyed && p137) {
          p137(p138);
        }
        return p138;
      });
    }
    if (vF40 && vF40.length) {
      v79 = f64(p136, vF40).then(function (p139) {
        vO12.pending.delete(vF295);
        if (vO12.destroyed) {
          return null;
        }
        if (p139) {
          f61(p136, p139);
        }
        if (p137) {
          p137(p139);
        }
        return p139;
      }, function (p140) {
        vO12.pending.delete(vF295);
        throw p140;
      });
      vO12.pending.set(vF295, v79);
      return v79;
    }
    v79 = vO12.requestChain.catch(function () {
      return null;
    }).then(function () {
      if (vO12.destroyed) {
        return null;
      }
      return f65(p136, vF233);
    }).then(function (p141) {
      vO12.pending.delete(vF295);
      if (vO12.destroyed) {
        return null;
      }
      if (p141) {
        f61(p136, p141);
      }
      if (p137) {
        p137(p141);
      }
      return p141;
    }, function (p142) {
      vO12.pending.delete(vF295);
      throw p142;
    });
    vO12.pending.set(vF295, v79);
    vO12.requestChain = v79.catch(function () {
      return null;
    });
    return v79;
  }
  function f73(p143) {
    return !!p143 && (p143.name === "saltQueueSummary" || p143.name === "saltQueueRoleId" || p143.name === "saltQueueRemaining" || p143.name === "saltQueueLockBox" || p143.name === "saltQueueLockCheck" || p143.name === "saltQueueLockText");
  }
  function f74(p144) {
    var vA11 = [];
    var v80;
    if (!p144) {
      return vA11;
    }
    if (typeof p144.numChildren === "number" && typeof p144.getChildAt === "function") {
      for (v80 = 0; v80 < p144.numChildren; v80++) {
        try {
          vA11.push(p144.getChildAt(v80));
        } catch (e21) {}
      }
    }
    if (Array.isArray(p144._children)) {
      vA11 = vA11.concat(p144._children);
    } else if (p144._children && Array.isArray(p144._children._items)) {
      vA11 = vA11.concat(p144._children._items);
    }
    return vA11.filter(function (p145, p146) {
      return p145 && vA11.indexOf(p145) === p146;
    });
  }
  function f75(p147, p148, p149, p150) {
    if (!p147 || p149 > 5) {
      return false;
    }
    p150 = p150 || [];
    if (p150.indexOf(p147) >= 0) {
      return false;
    }
    p150.push(p147);
    return f74(p147).some(function (p151) {
      if (p148(p151)) {
        return true;
      }
      return f75(p151, p148, p149 + 1, p150);
    });
  }
  function f76(p152) {
    return !!p152 && !f73(p152) && typeof p152.text === "string";
  }
  function f77(p153, p154) {
    var v81;
    for (v81 = 0; v81 < p154.length; v81++) {
      if (f76(p153 && p153[p154[v81]])) {
        return p153[p154[v81]];
      }
    }
    return null;
  }
  function f78(p155) {
    var vF77 = f77(p155, ["m_txtStatus", "m_txtState", "m_state", "m_status", "m_txtAction", "m_txtDesc"]);
    var vVF77 = vF77;
    if (vVF77) {
      return vVF77;
    }
    f75(p155, function (p156) {
      var v82;
      if (!f76(p156)) {
        return false;
      }
      v82 = String(p156.text || "");
      if (v82.indexOf("驻守") >= 0 || v82.indexOf("驻扎") >= 0 || v82.indexOf("驻防") >= 0 || v82.indexOf("防守") >= 0 || v82.indexOf("交战") >= 0 || v82.indexOf("行军") >= 0 || v82.indexOf("返回") >= 0) {
        vVF77 = p156;
        return true;
      }
      return false;
    }, 0);
    return vVF77;
  }
  function f79(p157) {
    var vF772 = f77(p157, ["m_strength", "m_txtStrength", "m_txtEnergy", "m_energy", "m_txtSpirit", "m_spirit"]);
    var vVF772 = vF772;
    if (vVF772) {
      return vVF772;
    }
    vVF772 = null;
    f75(p157, function (p158) {
      if (!f76(p158)) {
        return false;
      }
      if (String(p158.text || "").indexOf("精力") >= 0) {
        vVF772 = p158;
        return true;
      }
      return false;
    }, 0);
    return vVF772;
  }
  function f80(p159) {
    var v83 = null;
    f75(p159, function (p160) {
      if (!f76(p160)) {
        return false;
      }
      if (/^ID[:：]\s*\d+$/i.test(String(p160.text || "").trim())) {
        v83 = p160;
        return true;
      }
      return false;
    }, 0);
    return v83;
  }
  function f81(p161, p162) {
    var vF26 = f26(p162);
    var vF773 = f77(p161, ["m_txtName", "m_name", "m_txtPlayerName", "m_playerName", "m_txtRoleName", "m_roleName"]);
    var vVF773 = vF773;
    if (vVF773) {
      return vVF773;
    }
    if (!vF26) {
      return null;
    }
    f75(p161, function (p163) {
      var v84;
      if (!f76(p163)) {
        return false;
      }
      v84 = String(p163.text || "");
      if (v84 && (v84 === vF26 || v84.indexOf(vF26) >= 0 || vF26.indexOf(v84.replace(/\.\.\.$/, "")) >= 0)) {
        vVF773 = p163;
        return true;
      }
      return false;
    }, 0);
    return vVF773;
  }
  function f82(p164, p165) {
    if (!p165) {
      return;
    }
    if (p164) {
      ["font", "fontSize", "color", "bold", "italic", "underline", "stroke", "strokeColor", "shadowColor", "align", "verticalAlign", "leading", "letterSpacing"].forEach(function (p166) {
        if (p164[p166] !== undefined) {
          try {
            p165[p166] = p164[p166];
          } catch (e22) {}
        }
      });
    }
    if (!p165.fontSize) {
      p165.fontSize = 15;
    }
    if (!p165.color) {
      p165.color = "#d87532";
    }
  }
  function f83(p167, p168, p169) {
    if (!p167) {
      return;
    }
    if (typeof p167.setSize === "function") {
      p167.setSize(p168, p169);
    } else {
      p167.width = p168;
      p167.height = p169;
    }
  }
  function f84(p170, p171, p172) {
    if (!p170) {
      return;
    }
    if (typeof p170.setPosition === "function") {
      p170.setPosition(p171, p172);
    } else {
      p170.x = p171;
      p170.y = p172;
    }
  }
  function f85(p173) {
    var vString = String(p173 && p173.text || "");
    var vNumber2 = Number(p173 && p173.fontSize || 15);
    return Math.max(8, Math.ceil(vString.length * vNumber2 * 0.82));
  }
  function f86(p174, p175, p176, p177) {
    var vF19 = f19();
    if (!p174 || !vF19 || !vF19.GTextField) {
      return null;
    }
    if (p174[p175]) {
      if (vO12.items.indexOf(p174) < 0) {
        vO12.items.push(p174);
      }
      p174[p175].touchable = !!p177;
      p174[p175].singleLine = true;
      return p174[p175];
    }
    var v85 = new vF19.GTextField();
    v85.name = p176;
    v85.touchable = !!p177;
    v85.autoSize = vF19.AutoSizeType ? vF19.AutoSizeType.None : 0;
    v85.fontSize = 15;
    v85.color = "#d87532";
    v85.bold = false;
    v85.stroke = 0;
    v85.singleLine = true;
    v85.text = "";
    f83(v85, 120, 22);
    p174.addChild(v85);
    p174[p175] = v85;
    if (vO12.items.indexOf(p174) < 0) {
      vO12.items.push(p174);
    }
    return v85;
  }
  function f87(p178, p179, p180) {
    if (!p178 || !p179) {
      return;
    }
    var vF79 = f79(p178);
    var vF78 = f78(p178);
    var vF81 = f81(p178, p180);
    var v86 = vF79 || vF78 || vF81;
    var v87 = v86 && typeof v86.x === "number" ? v86.x : 118;
    var v88 = v86 && typeof v86.y === "number" ? v86.y : 28;
    var vV88 = v88;
    var v89 = p178.m_btnFight && typeof p178.m_btnFight.x === "number" ? p178.m_btnFight.x : (p178.width || 520) - 8;
    var v90;
    var v91;
    var v92;
    f82(vF79 || vF78 || vF81, p179);
    p179.bold = false;
    if (vF79) {
      v87 = vF79.x + f85(vF79) + 8;
      vV88 = vF79.y;
    } else if (vF78) {
      v87 = vF78.x + f85(vF78) + 8;
      vV88 = vF78.y;
    } else if (vF81) {
      v87 = Math.max(250, Math.min(v89 - 118, vF81.x + f85(vF81) + 10));
      vV88 = vF81.y;
    }
    v92 = v89 - 8;
    v87 = Math.min(v87, v92 - 1);
    v91 = f85(p179) + 4;
    v90 = Math.max(1, Math.min(v91, v92 - v87));
    f83(p179, v90, Number(vF79 && vF79.height) || Math.max(18, (p179.fontSize || 15) + 5));
    f84(p179, v87, vV88);
  }
  function f88(p181, p182) {
    if (!p181 || !p182) {
      return false;
    }
    var vF782 = f78(p181);
    var v93 = p181.m_btnFight && typeof p181.m_btnFight.x === "number" ? p181.m_btnFight.x : (p181.width || 520) - 8;
    var v94;
    var v95;
    if (!vF782) {
      return false;
    }
    f82(vF782, p182);
    v94 = vF782.x + f85(vF782) + 6;
    v95 = f85(p182) + 4;
    if (v94 + v95 > v93 - 8) {
      v94 = Math.max(vF782.x, v93 - v95 - 8);
    }
    f83(p182, v95, Number(vF782.height) || Math.max(18, (p182.fontSize || 15) + 5));
    f84(p182, v94, vF782.y);
    return true;
  }
  function f89(p183, p184, p185) {
    if (!p183 || !p184) {
      return;
    }
    var vF812 = f81(p183, p185);
    var vF792 = f79(p183);
    var v96 = vF792 || vF812;
    var v97 = vF812 || vF792;
    var v98;
    f82(v96, p184);
    v98 = Number(v96 && v96.fontSize || p184.fontSize || 15);
    p184.fontSize = Math.max(10, Math.min(13, v98 - 2));
    p184.bold = false;
    f83(p184, 90, p184.fontSize + 5);
    f84(p184, v97 && typeof v97.x === "number" ? v97.x : 105, Math.max(1, (vF812 && typeof vF812.y === "number" ? vF812.y : 22) - p184.fontSize - 2));
  }
  function f90(p186, p187, p188) {
    var vF86 = f86(p186, "__saltQueueSummaryText", "saltQueueSummary", false);
    if (!vF86) {
      return;
    }
    vF86.text = "阵容:" + (p188 && p188.label || "识别中");
    vF86.visible = true;
    vF86.touchable = false;
    f87(p186, vF86, p187);
  }
  function f91(p189, p190) {
    var vF862 = f86(p189, "__saltQueueRemainingText", "saltQueueRemaining", false);
    if (!vF862) {
      return;
    }
    vF862.text = p190 && p190.total ? p190.alive + "/" + p190.total : "--/5";
    vF862.touchable = false;
    vF862.visible = f88(p189, vF862);
  }
  function f92(p191, p192) {
    var vF234 = f23(p192);
    var vF80 = f80(p191);
    var v99;
    if (vF80 && vF80 !== p191.__saltQueueRoleIdText) {
      if (p191.__saltQueueRoleIdText) {
        p191.__saltQueueRoleIdText.visible = false;
      }
      return;
    }
    v99 = f86(p191, "__saltQueueRoleIdText", "saltQueueRoleId", false);
    if (!v99 || !vF234) {
      if (v99) {
        v99.visible = false;
      }
      return;
    }
    v99.text = "ID:" + vF234;
    v99.visible = true;
    v99.touchable = false;
    f89(p191, v99, p192);
  }
  function f93(p193, p194) {
    var v100 = p193 && p193.__saltQueueLockText;
    if (!p193) {
      return;
    }
    if (p193.__saltQueueLockBoxText) {
      p193.__saltQueueLockBoxText.visible = false;
      p193.__saltQueueLockBoxText.touchable = false;
    }
    if (p193.__saltQueueLockCheckText) {
      p193.__saltQueueLockCheckText.visible = false;
      p193.__saltQueueLockCheckText.touchable = false;
    }
    if (v100) {
      v100.visible = false;
      v100.touchable = false;
      v100.text = "";
    }
  }
  function f94(p195) {
    if (!p195) {
      return;
    }
    if (p195.__saltQueueSummaryText) {
      p195.__saltQueueSummaryText.visible = false;
    }
    if (p195.__saltQueueRoleIdText) {
      p195.__saltQueueRoleIdText.visible = false;
    }
    if (p195.__saltQueueRemainingText) {
      p195.__saltQueueRemainingText.visible = false;
    }
    if (p195.__saltQueueLockBoxText) {
      p195.__saltQueueLockBoxText.visible = false;
      p195.__saltQueueLockBoxText.touchable = false;
    }
    if (p195.__saltQueueLockCheckText) {
      p195.__saltQueueLockCheckText.visible = false;
      p195.__saltQueueLockCheckText.touchable = false;
    }
    if (p195.__saltQueueLockText) {
      p195.__saltQueueLockText.visible = false;
      p195.__saltQueueLockText.touchable = false;
    }
  }
  function f95(p196, p197) {
    return !!p196 && !!p197 && p196.__saltQueuePlayerKey === p197;
  }
  function f96(p198, p199) {
    if (vO12.destroyed || !p198) {
      return;
    }
    var v101;
    var v102;
    if (!f28(p199)) {
      f94(p198);
      p198.__saltQueuePlayer = null;
      p198.__saltQueuePlayerKey = "";
      return;
    }
    p198.__saltQueuePlayer = p199;
    v102 = f29(p199);
    p198.__saltQueuePlayerKey = v102;
    f92(p198, p199);
    f93(p198, p199);
    v101 = f60(p199);
    if (v101) {
      f90(p198, p199, v101);
      f91(p198, v101);
    } else {
      f90(p198, p199, null);
      f91(p198, null);
    }
    window.setTimeout(function () {
      if (vO12.destroyed || !f95(p198, v102)) {
        return;
      }
      f72(p199, function (p200) {
        if (vO12.destroyed || !f95(p198, v102)) {
          return;
        }
        if (p200) {
          f90(p198, p199, p200);
          f91(p198, p200);
        } else {
          f90(p198, p199, {
            label: "暂无数据"
          });
          f91(p198, null);
        }
      });
    }, 120);
  }
  function f97() {
    vO12.items.forEach(function (p201) {
      if (p201 && p201.__saltQueuePlayer) {
        f93(p201, p201.__saltQueuePlayer);
      }
    });
  }
  function f98() {
    f2("锁定功能已移除，仅保留阵容识别。");
    return false;
  }
  function f99(p202, p203) {
    var vA12 = ["__saltQueueOriginal" + p203, "__saltOriginal" + p203];
    var v103 = false;
    vA12.forEach(function (p204) {
      if (typeof p202[p204] === "function") {
        p202[p203] = p202[p204];
        try {
          delete p202[p204];
        } catch (e23) {
          p202[p204] = null;
        }
        v103 = true;
      }
    });
    try {
      delete p202.__saltTagsPatchVersion;
    } catch (e24) {}
    try {
      delete p202.__saltTagsPatched;
    } catch (e25) {}
    return v103;
  }
  function f100(p205, p206) {
    try {
      var vF1811 = f18(p205);
      var v104 = vF1811 && vF1811[p206];
      var v105 = v104 && v104.prototype;
      if (!v105 || v105.__saltQueueLockVersion === vLS20260725persistentow) {
        return false;
      }
      ["_refreshItem", "_refreshTeamItem"].forEach(function (p207) {
        f99(v105, p207);
        var v106 = "__saltQueueOriginal" + p207;
        var v107 = v105[p207];
        if (typeof v107 !== "function") {
          return;
        }
        v105[v106] = v107;
        v105[p207] = function (p208, p209, p210) {
          var v108 = v107.apply(this, arguments);
          window.setTimeout(function () {
            f96(p209, p210);
          }, 0);
          return v108;
        };
      });
      v105.__saltQueueLockVersion = vLS20260725persistentow;
      var vO28 = {
        moduleName: p205,
        exportName: p206
      };
      vO12.patched.push(vO28);
      f("已挂载队列名片:", p205);
      return true;
    } catch (e26) {
      f2("挂载队列名片失败:", p205, e26 && e26.message || e26);
      return false;
    }
  }
  function f101() {
    if (!f17()) {
      return false;
    }
    f100("AttackTroopsPage", "AttackTroopsPage");
    f100("DefenseTroopsPage", "DefenseTroopsPage");
    return f102("AttackTroopsPage", "AttackTroopsPage") && f102("DefenseTroopsPage", "DefenseTroopsPage");
  }
  function f102(p211, p212) {
    try {
      var vF1812 = f18(p211);
      var v109 = vF1812 && vF1812[p212];
      return !!v109 && !!v109.prototype && v109.prototype.__saltQueueLockVersion === vLS20260725persistentow;
    } catch (e27) {
      return false;
    }
  }
  function f103(p213, p214) {
    try {
      var vF1813 = f18(p213);
      var v110 = vF1813 && vF1813[p214];
      var v111 = v110 && v110.prototype;
      if (!v111) {
        return;
      }
      f99(v111, "_refreshItem");
      f99(v111, "_refreshTeamItem");
      try {
        delete v111.__saltQueueLockVersion;
      } catch (e28) {}
    } catch (e29) {}
  }
  function f104() {
    try {
      if (window.SaltFieldTargetTags && typeof window.SaltFieldTargetTags.destroy === "function") {
        window.SaltFieldTargetTags.destroy();
      }
    } catch (e30) {}
    ["salt-tags-ui", "salt-tags-mini", "salt-tags-style"].forEach(function (p215) {
      var v112 = document.getElementById(p215);
      if (v112 && v112.parentNode) {
        v112.parentNode.removeChild(v112);
      }
    });
  }
  function f105() {
    var vLN08 = 0;
    f104();
    f3();
    if (f101()) {
      return;
    }
    vO12.retryTimer = window.setInterval(function () {
      vLN08++;
      if (vO12.destroyed || f101() || vLN08 > 80) {
        window.clearInterval(vO12.retryTimer);
        vO12.retryTimer = 0;
      }
    }, 500);
  }
  function f106() {
    vO12.destroyed = true;
    if (vO12.retryTimer) {
      window.clearInterval(vO12.retryTimer);
      vO12.retryTimer = 0;
    }
    Array.from(vO12.activeRequests).forEach(function (p216) {
      try {
        p216();
      } catch (e31) {}
    });
    vO12.activeRequests.clear();
    f4();
    f103("AttackTroopsPage", "AttackTroopsPage");
    f103("DefenseTroopsPage", "DefenseTroopsPage");
    vO12.items.forEach(function (p217) {
      f94(p217);
      if (p217) {
        p217.__saltQueuePlayer = null;
      }
      if (p217) {
        p217.__saltQueuePlayerKey = "";
      }
    });
    vO12.items = [];
    vO12.teamCache.clear();
    vO12.formationCache.clear();
    vO12.pending.clear();
    vO12.imagePending.clear();
    delete window[vLSSaltQueueFormationLo];
  }
  var vO29 = {
    version: vLS20260725persistentow,
    lock: f98,
    attackLocked: function () {
      f2("锁定自动攻击功能已移除。");
      return false;
    },
    clearLock: function () {
      f97();
      return vO29;
    },
    getState: function () {
      return {
        version: vLS20260725persistentow,
        cacheSize: vO12.teamCache.size,
        formationCacheSize: vO12.formationCache.size,
        formationCacheHits: vO12.formationCacheHits,
        formationRecognitionRuns: vO12.formationRecognitionRuns,
        pendingRequests: vO12.pending.size,
        activeRequests: vO12.activeRequests.size,
        identityMode: "png-template-only",
        builtInHashes: 0,
        learnedHashes: 0,
        learnedHashBypass: false,
        templateCount: vA2.length,
        recognizableTemplateCount: vA2.filter(function (p218) {
          return Number(p218[0]) > 0;
        }).length,
        teamCacheTtlMs: vLN21600000,
        persistedTeamCacheTtlMs: vLN15552000000,
        persistedCacheKey: vLSBabayuSaltFieldForma,
        maxTeamCacheEntries: vLN1200,
        maxLearnedImageEntries: 0,
        imageMatchMaxDistance: vLN15,
        imageMatchMinMargin: vLN05,
        patched: vO12.patched.slice()
      };
    },
    testResponse: function (p219) {
      var vF474 = f47(p219);
      if (!Array.isArray(vF474)) {
        return null;
      }
      return f45({}, vF474);
    },
    getImageMap: function () {
      return {};
    },
    getLearnedImageMap: function () {
      return {};
    },
    clearLearnedImages: function () {
      f7();
      return vO29;
    },
    matchImage: function (p220) {
      return f16(p220);
    },
    learnImage: function (p221, p222) {
      p221 = f37(p221).toLowerCase();
      if (!p221) {
        return Promise.resolve({
          cached: false,
          match: null
        });
      }
      return f16(p222).then(function (p223) {
        var vO31 = {
          cached: false,
          match: p223
        };
        return vO31;
      });
    },
    identifyPlayer: function (p224) {
      return {
        roleCodeId: f23(p224),
        battlefieldId: f25(),
        cacheKey: f29(p224),
        name: f26(p224)
      };
    },
    identifyFormation: function (p225) {
      return f72(p225);
    },
    listParticipants: function () {
      return f35();
    },
    destroy: f106
  };
  f10();
  window[vLSSaltQueueFormationLo] = vO29;
  f105();
  f("已加载：队列阵容识别、PNG 头像模板比对与玩家 ID 阵容缓存。无内置或学习 hash 直认。锁定自动攻击已移除。");
})();