module.exports = {
  apps: [
    {
      name: 'xyzw-backend',
      cwd: './backend',
      script: 'src/index.js',
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      watch: false,
      max_memory_restart: '512M',
      env: {
        NODE_ENV: 'production',
        HOST: '0.0.0.0',
        PORT: 3001,
        DB_PATH: './data/xyzw.db',

        // Replace these before production use.
        JWT_SECRET: 'replace_with_a_strong_jwt_secret',
        ENCRYPTION_KEY: 'replace_with_a_strong_32_byte_key',

        GAME_CLIENT_VERSION: '2.3.9-wx',
        GAME_BATTLE_VERSION: 241201,
        MAX_CONCURRENT_ACCOUNTS: 5,
        ZENPROXY_API_KEY: process.env.ZENPROXY_API_KEY || '',
        ZENPROXY_COUNTRIES: process.env.ZENPROXY_COUNTRIES || '',
        ZENPROXY_LOCAL_CLIENT_ENABLED: process.env.ZENPROXY_LOCAL_CLIENT_ENABLED || '1',
        ZENPROXY_LOCAL_CONTROLLER_URL: process.env.ZENPROXY_LOCAL_CONTROLLER_URL || 'http://127.0.0.1:9090',
        ZENPROXY_LOCAL_SECRET: process.env.ZENPROXY_LOCAL_SECRET || 'xyzw-zenproxy-local',
        ZENPROXY_SERVER_URL: process.env.ZENPROXY_SERVER_URL || 'https://zenproxy.top',
        ZENPROXY_FETCH_COUNT: process.env.ZENPROXY_FETCH_COUNT || '100',
        ZENPROXY_FETCH_COUNTRY: process.env.ZENPROXY_FETCH_COUNTRY || '',
        ZENPROXY_FETCH_TYPE: process.env.ZENPROXY_FETCH_TYPE || '',
        ZENPROXY_FETCH_CHATGPT: process.env.ZENPROXY_FETCH_CHATGPT || '',
        ZENPROXY_PORT_START: process.env.ZENPROXY_PORT_START || '20001',
        ZENPROXY_PORT_END: process.env.ZENPROXY_PORT_END || '20100',
        PROXY_VALIDATION_URL: process.env.PROXY_VALIDATION_URL || 'https://httpbin.org/ip',
        PROXY_VALIDATION_TIMEOUT_MS: process.env.PROXY_VALIDATION_TIMEOUT_MS || '10000',
        PROXY_VALIDATION_CONCURRENCY: process.env.PROXY_VALIDATION_CONCURRENCY || '10',
        PROXY_VALIDATION_MAX_RESPONSE_MS: process.env.PROXY_VALIDATION_MAX_RESPONSE_MS || '15000',
      },
    },
    {
      name: 'zenproxy-singbox',
      cwd: './zenproxy-runtime',
      script: './sing-box',
      args: 'run -c config.json',
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      watch: false,
      max_memory_restart: '512M',
      env: {
        NODE_ENV: 'production',
      },
    },
  ],
};
